syntax = "proto3";

option go_package = "github.com/ballinwza/scraper-dashboard-be/api/proto/v1;grpc_api";

package chat.v1;

service ChatGRPC {
  rpc Query (ChatRequest) returns (ChatResponse) {}
  rpc UploadPdf (stream UploadPdfRequest) returns (UploadPdfResponse);
}

// Query
message ChatRequest {
  string question = 1; // เช่น "สรุปเอกสาร"
}

message ChatResponse {
  string message = 1;  // ข้อความแจ้งสถานะการทำงาน
}

// UploadPdf
message PdfMetadata {
  string filename = 1;
  int64  file_size = 2;
}

message UploadPdfRequest {
  oneof data {
    PdfMetadata metadata = 1;
    bytes chunk_data     = 2; 
  }
}

message UploadPdfResponse {
  string file_id = 1;
  bool success   = 2;
  string message = 3;
}

