version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: scraper-backend
    ports:
      - "8080:8080"
    # อ่านไฟล์ .env บน local
    env_file:
      - .env
    restart: unless-stopped