package handler

import (
	"io"
	"net/http"

	"github.com/ballinwza/scraper-dashboard-be/config"
	usecase_rag "github.com/ballinwza/scraper-dashboard-be/internal/usecase/rag"
	"github.com/ballinwza/scraper-dashboard-be/pkg/validator"
	"github.com/gin-gonic/gin"
)

type RagHandler struct {
	usecase usecase_rag.IRagUsecase
	cfg     config.Config
}

func NewRagHandler(
	usecase usecase_rag.IRagUsecase,
	cfg config.Config,
) *RagHandler {
	return &RagHandler{
		usecase: usecase,
		cfg:     cfg,
	}
}

// GenerateAnswer
// @Summary Ask question for answer
// @Description The answer generated by AI Rag
// @Tags RAG
// @Accept json
// @Produce json
// @Param request body generateAnswerRequest true "Question Request"
// @Success 200 {object} generateAnswerResponse
// @Failure 400 {object} errorResponse
// @Router /rag/qna [post]
func (h *RagHandler) AskQuestion(c *gin.Context) {
	var req generateAnswerRequest
	validator := validator.New()

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	if errs := validator.ValidateStruct(&req); len(errs) > 0 {
		c.JSON(http.StatusUnprocessableEntity, gin.H{"errors": errs})
		return
	}

	answer, err := h.usecase.GenerateAnswer(
		c.Request.Context(),
		req.Question,
	)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	res := generateAnswerResponse{
		Message: answer,
	}

	c.JSON(http.StatusOK, res)
}

// UploadPdf
// @Summary Upload PDF/Image file
// @Description Receive multipart file, read bytes, and process via RAG UseCase (gRPC)
// @Tags RAG
// @Accept multipart/form-data
// @Produce json
// @Param file formData file true "Document File"
// @Success 200 {object} map[string]string
// @Failure 400 {object} errorResponse
// @Failure 500 {object} errorResponse
// @Router /rag/upload [post]
func (h *RagHandler) RecieverOfUplodFile(c *gin.Context) {
	fileHeader, err := c.FormFile("file")
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Failed to get file from request: " + err.Error()})
		return
	}

	// 2. เปิดไฟล์เพื่ออ่านข้อมูล
	file, err := fileHeader.Open()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to open file: " + err.Error()})
		return
	}
	defer file.Close()

	filename := fileHeader.Filename
	// contentType := fileHeader.Header.Get("Content-Type")

	// 3. อ่านเนื้อหาไฟล์ทั้งหมดให้อยู่ในรูปแบบ []byte ก้อนเดียว
	fileBytes, err := io.ReadAll(file)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to read file bytes: " + err.Error()})
		return
	}
	result, err := h.usecase.ReceiverOfUploadFile(
		c.Request.Context(),
		fileBytes,
		filename,
		// contentType,
	)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// res := generateAnswerResponse{
	// 	Message: answer,
	// }

	c.JSON(http.StatusOK, gin.H{
		"message": "File uploaded successfully",
		"data":    result,
	})

	// c.JSON(http.StatusOK, res)
}
