// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout user session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login with username, password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Loging into system",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Receive refresh_token from cookie to refreshing refreshToken in data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh all token of user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cookie: refresh_token=...",
                        "name": "refresh_token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access Token succesfully",
                        "schema": {
                            "$ref": "#/definitions/handler.refreshResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "refresh_token=...; Path=/; HttpOnly; Secure; SameSite=Strict"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad input request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Cookie missing or Token Invalid",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user with username, password, and name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/chat-sessions/create": {
            "post": {
                "description": "Create a new chat session for a specific chatbot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat Session"
                ],
                "summary": "Create Chat Session",
                "parameters": [
                    {
                        "description": "Create Chat Session Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateChatSessionReqDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateChatSessionResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chat-sessions/delete": {
            "delete": {
                "description": "Delete a chat session by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat Session"
                ],
                "summary": "Delete Chat Session",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteChatSessionReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chat-sessions/list": {
            "post": {
                "description": "Get a paginated list of chat sessions for a user or chatbot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat Session"
                ],
                "summary": "List Chat Sessions",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ListChatSessionsReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListChatSessionsResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chat-sessions/messages": {
            "post": {
                "description": "Add a new chat message to an existing session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat Session"
                ],
                "summary": "Add Chat Message",
                "parameters": [
                    {
                        "description": "Add Chat Message Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddChatMessageReqDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AddChatMessageResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chat-sessions/{id}": {
            "get": {
                "description": "Get specific chat session details and message history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat Session"
                ],
                "summary": "Get Chat Session by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetChatSessionResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chatbots/create": {
            "post": {
                "description": "Create a new chatbot blueprint for a specific user/tenant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chatbot"
                ],
                "summary": "Create Multi-Tenant Chatbot",
                "parameters": [
                    {
                        "description": "Create Chatbot Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMultiTenantChatbotReqDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMultiTenantChatbotResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chatbots/delete": {
            "delete": {
                "description": "Delete a chatbot blueprint by ID and User ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chatbot"
                ],
                "summary": "Delete Multi-Tenant Chatbot",
                "parameters": [
                    {
                        "description": "Update Chatbot Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteMultiTenantChatbotReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteMultiTenantChatbotResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chatbots/list": {
            "post": {
                "description": "Get a paginated list of chatbot blueprints for a specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chatbot"
                ],
                "summary": "List Multi-Tenant Chatbots",
                "parameters": [
                    {
                        "description": "Create Chat Session Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ListMultiTenantChatbotsReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListMultiTenantChatbotsResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chatbots/update": {
            "post": {
                "description": "Update details of an existing chatbot blueprint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chatbot"
                ],
                "summary": "Update Multi-Tenant Chatbot",
                "parameters": [
                    {
                        "description": "Update Chatbot Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMultiTenantChatbotReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMultiTenantChatbotResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/chatbots/{id}": {
            "get": {
                "description": "Get specific chatbot blueprint details by its ID and User ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chatbot"
                ],
                "summary": "Get Multi-Tenant Chatbot by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chatbot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetMultiTenantChatbotResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/knowledge-files/delete": {
            "delete": {
                "description": "Delete a knowledge file associated with a chatbot and user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Knowledge File"
                ],
                "summary": "Delete Knowledge File",
                "parameters": [
                    {
                        "description": "Delete Knowledge File Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteKnowledgeFileReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain_ai_estate_rag.DeleteKnowledgeFileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/knowledge-files/list": {
            "post": {
                "description": "Get a paginated list of knowledge files for a chatbot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Knowledge File"
                ],
                "summary": "List Knowledge Files",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ListKnowledgeFilesReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain_ai_estate_rag.ListKnowledgeFilesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/knowledge-files/upload": {
            "post": {
                "description": "Uploads a PDF or Image file using streaming gRPC underneath",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "Upload file (PDF/Image) to Multi-Tenant RAG",
                "parameters": [
                    {
                        "description": "Upload Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UploadFileMultiTenantReqDTO"
                        }
                    },
                    {
                        "type": "file",
                        "description": "File to upload (PDF, PNG, JPG, WEBP)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain_ai_estate_rag.UploadFileMultiTenantResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload or file type",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/knowledge-files/{id}": {
            "get": {
                "description": "Get specific knowledge file details by its ID and User ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Knowledge File"
                ],
                "summary": "Get Knowledge File by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain_ai_estate_rag.GetKnowledgeFileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rag/qna": {
            "post": {
                "description": "The answer generated by AI Rag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "Ask question for answer",
                "parameters": [
                    {
                        "description": "Question Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.generateAnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.generateAnswerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rag/search-similar": {
            "post": {
                "description": "Search similar content from knowledge base using vector similarity search",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "Search Similar Knowledge (RAG)",
                "parameters": [
                    {
                        "description": "Search Similar Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SearchSimilarReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SearchSimilarResDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rag/upload": {
            "post": {
                "description": "Receive multipart file, read bytes, and process via RAG UseCase (gRPC)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "Upload PDF/Image file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Document File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rental/estate/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rental Estates"
                ],
                "summary": "ดึงรายละเอียดเชิงลึกของอสังหาริมทรัพย์รายชิ้น",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Estate ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.rentalEstateResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rental Estates"
                ],
                "summary": "ลบรายการอสังหาริมทรัพย์ที่ไม่อัปเดตหรือซ้ำซ้อน",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Estate ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rental/estates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rental Estates"
                ],
                "summary": "ดึงรายการข้อมูลอสังหาฯ (Pagination, Filtering, Sorting)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum price",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum price",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc/desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.rentalEstatePaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rental/estates/export": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "Rental Estates"
                ],
                "summary": "ส่งออกข้อมูลอสังหาฯ ที่เลือกหรือค้นหาออกมาเป็นไฟล์ CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum price",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum price",
                        "name": "max_price",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/scraper/rental-estate": {
            "post": {
                "description": "Scrapping Manualy by Target URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraper Controls"
                ],
                "summary": "Trigger Scraper Job",
                "parameters": [
                    {
                        "description": "Target URL Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.triggerScraperRentalEstateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Scraper job started successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "406": {
                        "description": "Avaliable for admin only",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to start scraper job",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get user details by username after authenticationo scuccess",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User by Username",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.userResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.RentalEstate": {
            "type": "object",
            "properties": {
                "area_sqm": {
                    "type": "number"
                },
                "bathrooms": {
                    "type": "integer"
                },
                "bedrooms": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "date_posted": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "formal_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                },
                "property_type": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain_ai_estate_rag.Chunk": {
            "type": "object",
            "properties": {
                "chunk_index": {
                    "type": "integer"
                },
                "page_number": {
                    "type": "integer"
                },
                "text_content": {
                    "type": "string"
                },
                "token_count": {
                    "type": "integer"
                },
                "vector_id": {
                    "type": "string"
                }
            }
        },
        "domain_ai_estate_rag.DeleteKnowledgeFileResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain_ai_estate_rag.FileStatus": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "FileStatusPending",
                "FileStatusCompleted",
                "FileStatusFailed"
            ]
        },
        "domain_ai_estate_rag.GetKnowledgeFileResponse": {
            "type": "object",
            "properties": {
                "file": {
                    "$ref": "#/definitions/domain_ai_estate_rag.KnowledgeFile"
                }
            }
        },
        "domain_ai_estate_rag.KnowledgeFile": {
            "type": "object",
            "properties": {
                "chatbot_id": {
                    "type": "string"
                },
                "chunks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain_ai_estate_rag.Chunk"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "error_message": {
                    "description": "optional",
                    "type": "string"
                },
                "file_size_bytes": {
                    "type": "integer"
                },
                "file_type": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain_ai_estate_rag.FileStatus"
                },
                "text_content": {
                    "description": "optional",
                    "type": "string"
                },
                "total_chunks": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain_ai_estate_rag.ListKnowledgeFilesResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain_ai_estate_rag.KnowledgeFile"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "domain_ai_estate_rag.UploadFileMultiTenantResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "file_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain_ai_estate_rag.FileStatus"
                },
                "total_bytes": {
                    "type": "integer"
                },
                "total_chunks": {
                    "type": "integer"
                }
            }
        },
        "dto.AddChatMessageReqDTO": {
            "type": "object",
            "required": [
                "content",
                "role",
                "session_id"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "สวัสดีครับ มีโปรโมชั่นคอนโดอะไรบ้าง"
                },
                "role": {
                    "type": "string",
                    "example": "USER"
                },
                "session_id": {
                    "type": "string",
                    "example": "65f1a2b3c4d5e6f7a8b9c0d1"
                }
            }
        },
        "dto.AddChatMessageResDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/dto.ChatMessageResDTO"
                }
            }
        },
        "dto.ChatMessageResDTO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "สวัสดีครับ มีโปรโมชั่นคอนโดอะไรบ้าง"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-08-18T10:00:00Z"
                },
                "role": {
                    "type": "string",
                    "example": "USER"
                }
            }
        },
        "dto.ChatSessionResDTO": {
            "type": "object",
            "properties": {
                "chatbot_id": {
                    "type": "string",
                    "example": "bot-888"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-08-18T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "65f1a2b3c4d5e6f7a8b9c0d1"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ChatMessageResDTO"
                    }
                },
                "session_title": {
                    "type": "string",
                    "example": "สอบถามข้อมูลโปรโมชั่น"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-08-18T10:05:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "user-999"
                }
            }
        },
        "dto.ChatbotBlueprintResDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-08-18T10:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "บอทสำหรับตอบคำถามและดูแลลูกค้า"
                },
                "id": {
                    "type": "string",
                    "example": "65f1a2b3c4d5e6f7a8b9c0d1"
                },
                "name": {
                    "type": "string",
                    "example": "Customer Support Bot"
                },
                "system_prompt": {
                    "type": "string",
                    "example": "You are a helpful assistant."
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-08-18T10:05:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "user-999"
                }
            }
        },
        "dto.CreateChatSessionReqDTO": {
            "type": "object",
            "required": [
                "chatbot_id"
            ],
            "properties": {
                "chatbot_id": {
                    "type": "string",
                    "example": "bot-888"
                },
                "session_title": {
                    "type": "string",
                    "example": "สอบถามข้อมูลโปรโมชั่น"
                }
            }
        },
        "dto.CreateChatSessionResDTO": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/dto.ChatSessionResDTO"
                }
            }
        },
        "dto.CreateMultiTenantChatbotReqDTO": {
            "type": "object",
            "required": [
                "name",
                "system_prompt"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "บอทสำหรับตอบคำถามและดูแลลูกค้า"
                },
                "name": {
                    "type": "string",
                    "example": "Customer Support Bot"
                },
                "system_prompt": {
                    "type": "string",
                    "example": "You are a helpful assistant."
                }
            }
        },
        "dto.CreateMultiTenantChatbotResDTO": {
            "type": "object",
            "properties": {
                "chatbot": {
                    "$ref": "#/definitions/dto.ChatbotBlueprintResDTO"
                }
            }
        },
        "dto.DeleteChatSessionReqDTO": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "65f1a2b3c4d5e6f7a8b9c0d1"
                }
            }
        },
        "dto.DeleteKnowledgeFileReqDTO": {
            "type": "object",
            "required": [
                "chatbot_id"
            ],
            "properties": {
                "chatbot_id": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteMultiTenantChatbotReqDTO": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "65f1a2b3c4d5e6f7a8b9c0d1"
                }
            }
        },
        "dto.DeleteMultiTenantChatbotResDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Chatbot deleted successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.GetChatSessionResDTO": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/dto.ChatSessionResDTO"
                }
            }
        },
        "dto.GetMultiTenantChatbotResDTO": {
            "type": "object",
            "properties": {
                "chatbot": {
                    "$ref": "#/definitions/dto.ChatbotBlueprintResDTO"
                }
            }
        },
        "dto.ListChatSessionsReqDTO": {
            "type": "object",
            "properties": {
                "chatbot_id": {
                    "type": "string",
                    "example": "bot-888"
                },
                "page_size": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1,
                    "example": 20
                },
                "page_token": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                }
            }
        },
        "dto.ListChatSessionsResDTO": {
            "type": "object",
            "properties": {
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ChatSessionResDTO"
                    }
                },
                "total_count": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "dto.ListKnowledgeFilesReqDTO": {
            "type": "object",
            "required": [
                "chatbot_id"
            ],
            "properties": {
                "chatbot_id": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer",
                    "default": 10
                },
                "offset": {
                    "type": "integer",
                    "default": 0
                }
            }
        },
        "dto.ListMultiTenantChatbotsReqDTO": {
            "type": "object",
            "properties": {
                "page_size": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1,
                    "example": 10
                },
                "page_token": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                }
            }
        },
        "dto.ListMultiTenantChatbotsResDTO": {
            "type": "object",
            "properties": {
                "chatbots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ChatbotBlueprintResDTO"
                    }
                },
                "next_page_token": {
                    "type": "integer",
                    "example": 10
                },
                "total_count": {
                    "type": "integer",
                    "example": 25
                }
            }
        },
        "dto.MetadataVectorRecordDTO": {
            "type": "object",
            "properties": {
                "chatbot_id": {
                    "type": "string",
                    "example": "bot-888"
                },
                "chunk_index": {
                    "type": "integer",
                    "example": 1
                },
                "file_id": {
                    "type": "string",
                    "example": "file-123"
                },
                "filename": {
                    "type": "string",
                    "example": "document.pdf"
                },
                "page_number": {
                    "type": "integer",
                    "example": 5
                },
                "text_content": {
                    "type": "string",
                    "example": "เนื้อหาในเอกสารที่ค้นพบ..."
                },
                "user_id": {
                    "type": "string",
                    "example": "user-999"
                }
            }
        },
        "dto.SearchSimilarReqDTO": {
            "type": "object",
            "required": [
                "chatbot_id",
                "query_text"
            ],
            "properties": {
                "chatbot_id": {
                    "type": "string",
                    "example": "bot-888"
                },
                "knowledge_file_id": {
                    "type": "string",
                    "example": "file-123"
                },
                "query_text": {
                    "type": "string",
                    "example": "สอบถามข้อมูลโปรโมชั่น"
                },
                "top_k": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "dto.SearchSimilarResDTO": {
            "type": "object",
            "properties": {
                "answer_message": {
                    "type": "string",
                    "example": "นี่คือคำตอบจากระบบ..."
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SearchVectorRecordItemDTO"
                    }
                }
            }
        },
        "dto.SearchVectorRecordItemDTO": {
            "type": "object",
            "properties": {
                "record": {
                    "$ref": "#/definitions/dto.VectorRecordDTO"
                },
                "score": {
                    "type": "number",
                    "example": 0.895
                }
            }
        },
        "dto.UpdateMultiTenantChatbotReqDTO": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Updated description"
                },
                "id": {
                    "type": "string",
                    "example": "65f1a2b3c4d5e6f7a8b9c0d1"
                },
                "name": {
                    "type": "string",
                    "example": "Updated Bot Name"
                },
                "system_prompt": {
                    "type": "string",
                    "example": "Updated system prompt"
                }
            }
        },
        "dto.UpdateMultiTenantChatbotResDTO": {
            "type": "object",
            "properties": {
                "chatbot": {
                    "$ref": "#/definitions/dto.ChatbotBlueprintResDTO"
                }
            }
        },
        "dto.UploadFileMultiTenantReqDTO": {
            "type": "object",
            "required": [
                "chatbot_id"
            ],
            "properties": {
                "chatbot_id": {
                    "type": "string"
                }
            }
        },
        "dto.VectorRecordDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "vector-uuid-123"
                },
                "metadata": {
                    "$ref": "#/definitions/dto.MetadataVectorRecordDTO"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "handler.apiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operation successful"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request payload"
                }
            }
        },
        "handler.generateAnswerRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "question": {
                    "type": "string",
                    "default": "สรุปเอกสารย่อๆ"
                }
            }
        },
        "handler.generateAnswerResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.loginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "handler.refreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "d3f78a9c2b4e8f110a1290bc5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f"
                }
            }
        },
        "handler.registerRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.registerResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.rentalEstatePaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RentalEstate"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/handler.rentalEstatePaginationMetaResponse"
                }
            }
        },
        "handler.rentalEstatePaginationMetaResponse": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer",
                    "example": 1
                },
                "has_next": {
                    "type": "boolean",
                    "example": true
                },
                "has_prev": {
                    "type": "boolean",
                    "example": false
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "total_items": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "handler.rentalEstateResponse": {
            "type": "object",
            "properties": {
                "area_sqm": {
                    "type": "number"
                },
                "bathrooms": {
                    "type": "integer"
                },
                "bedrooms": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "date_posted": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "formal_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                },
                "property_type": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.triggerScraperRentalEstateRequest": {
            "type": "object",
            "required": [
                "target_url"
            ],
            "properties": {
                "max_page": {
                    "type": "integer",
                    "example": 1
                },
                "start_page": {
                    "type": "integer",
                    "example": 1
                },
                "target_url": {
                    "type": "string",
                    "example": "https://www.dotproperty.co.th/en/condos-for-rent/bangkok"
                }
            }
        },
        "handler.userResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Scraper & Data Aggregator API",
	Description:      "API Service สำหรับจัดการข้อมูล Scraping และแสดงผลบน Dashboard",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
