// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: ai_estate_rag.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatGRPC_Query_FullMethodName     = "/chat.v1.ChatGRPC/Query"
	ChatGRPC_UploadPdf_FullMethodName = "/chat.v1.ChatGRPC/UploadPdf"
)

// ChatGRPCClient is the client API for ChatGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatGRPCClient interface {
	Query(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	UploadPdf(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPdfRequest, UploadPdfResponse], error)
}

type chatGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewChatGRPCClient(cc grpc.ClientConnInterface) ChatGRPCClient {
	return &chatGRPCClient{cc}
}

func (c *chatGRPCClient) Query(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, ChatGRPC_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatGRPCClient) UploadPdf(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPdfRequest, UploadPdfResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatGRPC_ServiceDesc.Streams[0], ChatGRPC_UploadPdf_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadPdfRequest, UploadPdfResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatGRPC_UploadPdfClient = grpc.ClientStreamingClient[UploadPdfRequest, UploadPdfResponse]

// ChatGRPCServer is the server API for ChatGRPC service.
// All implementations must embed UnimplementedChatGRPCServer
// for forward compatibility.
type ChatGRPCServer interface {
	Query(context.Context, *ChatRequest) (*ChatResponse, error)
	UploadPdf(grpc.ClientStreamingServer[UploadPdfRequest, UploadPdfResponse]) error
	mustEmbedUnimplementedChatGRPCServer()
}

// UnimplementedChatGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatGRPCServer struct{}

func (UnimplementedChatGRPCServer) Query(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedChatGRPCServer) UploadPdf(grpc.ClientStreamingServer[UploadPdfRequest, UploadPdfResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadPdf not implemented")
}
func (UnimplementedChatGRPCServer) mustEmbedUnimplementedChatGRPCServer() {}
func (UnimplementedChatGRPCServer) testEmbeddedByValue()                  {}

// UnsafeChatGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatGRPCServer will
// result in compilation errors.
type UnsafeChatGRPCServer interface {
	mustEmbedUnimplementedChatGRPCServer()
}

func RegisterChatGRPCServer(s grpc.ServiceRegistrar, srv ChatGRPCServer) {
	// If the following call panics, it indicates UnimplementedChatGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatGRPC_ServiceDesc, srv)
}

func _ChatGRPC_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatGRPCServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatGRPC_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatGRPCServer).Query(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatGRPC_UploadPdf_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatGRPCServer).UploadPdf(&grpc.GenericServerStream[UploadPdfRequest, UploadPdfResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatGRPC_UploadPdfServer = grpc.ClientStreamingServer[UploadPdfRequest, UploadPdfResponse]

// ChatGRPC_ServiceDesc is the grpc.ServiceDesc for ChatGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.v1.ChatGRPC",
	HandlerType: (*ChatGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _ChatGRPC_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadPdf",
			Handler:       _ChatGRPC_UploadPdf_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ai_estate_rag.proto",
}
