// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: ai_estate_rag.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"` // เช่น "สรุปเอกสาร"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_estate_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_estate_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_estate_rag_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // ข้อความแจ้งสถานะการทำงาน
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ai_estate_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_estate_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_estate_rag_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UploadPdf
type PdfMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfMetadata) Reset() {
	*x = PdfMetadata{}
	mi := &file_ai_estate_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfMetadata) ProtoMessage() {}

func (x *PdfMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ai_estate_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfMetadata.ProtoReflect.Descriptor instead.
func (*PdfMetadata) Descriptor() ([]byte, []int) {
	return file_ai_estate_rag_proto_rawDescGZIP(), []int{2}
}

func (x *PdfMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PdfMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadPdfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadPdfRequest_Metadata
	//	*UploadPdfRequest_ChunkData
	Data          isUploadPdfRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPdfRequest) Reset() {
	*x = UploadPdfRequest{}
	mi := &file_ai_estate_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPdfRequest) ProtoMessage() {}

func (x *UploadPdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_estate_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPdfRequest.ProtoReflect.Descriptor instead.
func (*UploadPdfRequest) Descriptor() ([]byte, []int) {
	return file_ai_estate_rag_proto_rawDescGZIP(), []int{3}
}

func (x *UploadPdfRequest) GetData() isUploadPdfRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadPdfRequest) GetMetadata() *PdfMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadPdfRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadPdfRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadPdfRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadPdfRequest_Data interface {
	isUploadPdfRequest_Data()
}

type UploadPdfRequest_Metadata struct {
	Metadata *PdfMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadPdfRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadPdfRequest_Metadata) isUploadPdfRequest_Data() {}

func (*UploadPdfRequest_ChunkData) isUploadPdfRequest_Data() {}

type UploadPdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPdfResponse) Reset() {
	*x = UploadPdfResponse{}
	mi := &file_ai_estate_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPdfResponse) ProtoMessage() {}

func (x *UploadPdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_estate_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPdfResponse.ProtoReflect.Descriptor instead.
func (*UploadPdfResponse) Descriptor() ([]byte, []int) {
	return file_ai_estate_rag_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPdfResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadPdfResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadPdfResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ai_estate_rag_proto protoreflect.FileDescriptor

const file_ai_estate_rag_proto_rawDesc = "" +
	"\n" +
	"\x13ai_estate_rag.proto\x12\achat.v1\")\n" +
	"\vChatRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"(\n" +
	"\fChatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"F\n" +
	"\vPdfMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\"o\n" +
	"\x10UploadPdfRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.chat.v1.PdfMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"`\n" +
	"\x11UploadPdfResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x88\x01\n" +
	"\bChatGRPC\x126\n" +
	"\x05Query\x12\x14.chat.v1.ChatRequest\x1a\x15.chat.v1.ChatResponse\"\x00\x12D\n" +
	"\tUploadPdf\x12\x19.chat.v1.UploadPdfRequest\x1a\x1a.chat.v1.UploadPdfResponse(\x01BAZ?github.com/ballinwza/scraper-dashboard-be/api/proto/v1;grpc_apib\x06proto3"

var (
	file_ai_estate_rag_proto_rawDescOnce sync.Once
	file_ai_estate_rag_proto_rawDescData []byte
)

func file_ai_estate_rag_proto_rawDescGZIP() []byte {
	file_ai_estate_rag_proto_rawDescOnce.Do(func() {
		file_ai_estate_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_estate_rag_proto_rawDesc), len(file_ai_estate_rag_proto_rawDesc)))
	})
	return file_ai_estate_rag_proto_rawDescData
}

var file_ai_estate_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_estate_rag_proto_goTypes = []any{
	(*ChatRequest)(nil),       // 0: chat.v1.ChatRequest
	(*ChatResponse)(nil),      // 1: chat.v1.ChatResponse
	(*PdfMetadata)(nil),       // 2: chat.v1.PdfMetadata
	(*UploadPdfRequest)(nil),  // 3: chat.v1.UploadPdfRequest
	(*UploadPdfResponse)(nil), // 4: chat.v1.UploadPdfResponse
}
var file_ai_estate_rag_proto_depIdxs = []int32{
	2, // 0: chat.v1.UploadPdfRequest.metadata:type_name -> chat.v1.PdfMetadata
	0, // 1: chat.v1.ChatGRPC.Query:input_type -> chat.v1.ChatRequest
	3, // 2: chat.v1.ChatGRPC.UploadPdf:input_type -> chat.v1.UploadPdfRequest
	1, // 3: chat.v1.ChatGRPC.Query:output_type -> chat.v1.ChatResponse
	4, // 4: chat.v1.ChatGRPC.UploadPdf:output_type -> chat.v1.UploadPdfResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_estate_rag_proto_init() }
func file_ai_estate_rag_proto_init() {
	if File_ai_estate_rag_proto != nil {
		return
	}
	file_ai_estate_rag_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadPdfRequest_Metadata)(nil),
		(*UploadPdfRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_estate_rag_proto_rawDesc), len(file_ai_estate_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_estate_rag_proto_goTypes,
		DependencyIndexes: file_ai_estate_rag_proto_depIdxs,
		MessageInfos:      file_ai_estate_rag_proto_msgTypes,
	}.Build()
	File_ai_estate_rag_proto = out.File
	file_ai_estate_rag_proto_goTypes = nil
	file_ai_estate_rag_proto_depIdxs = nil
}
