// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: chatbot.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatbotService_CreateMultiTenantChatbot_FullMethodName = "/chatbot.v1.ChatbotService/CreateMultiTenantChatbot"
	ChatbotService_GetMultiTenantChatbot_FullMethodName    = "/chatbot.v1.ChatbotService/GetMultiTenantChatbot"
	ChatbotService_ListMultiTenantChatbots_FullMethodName  = "/chatbot.v1.ChatbotService/ListMultiTenantChatbots"
	ChatbotService_UpdateMultiTenantChatbot_FullMethodName = "/chatbot.v1.ChatbotService/UpdateMultiTenantChatbot"
	ChatbotService_DeleteMultiTenantChatbot_FullMethodName = "/chatbot.v1.ChatbotService/DeleteMultiTenantChatbot"
)

// ChatbotServiceClient is the client API for ChatbotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service สำหรับจัดการ Chatbot Blueprint / Profile Operations
type ChatbotServiceClient interface {
	// สร้าง Chatbot Blueprint ใหม่
	CreateMultiTenantChatbot(ctx context.Context, in *CreateMultiTenantChatbotRequest, opts ...grpc.CallOption) (*CreateMultiTenantChatbotResponse, error)
	// ดึงข้อมูล Chatbot Blueprint ตาม ID
	GetMultiTenantChatbot(ctx context.Context, in *GetMultiTenantChatbotRequest, opts ...grpc.CallOption) (*GetMultiTenantChatbotResponse, error)
	// ดึงรายการ Chatbot Blueprint ทั้งหมดของผู้ใช้ (รองรับ Pagination)
	ListMultiTenantChatbots(ctx context.Context, in *ListMultiTenantChatbotsRequest, opts ...grpc.CallOption) (*ListMultiTenantChatbotsResponse, error)
	// แก้ไขข้อมูล Chatbot Blueprint (ใช้ FieldMask สำหรับ Partial Update)
	UpdateMultiTenantChatbot(ctx context.Context, in *UpdateMultiTenantChatbotRequest, opts ...grpc.CallOption) (*UpdateMultiTenantChatbotResponse, error)
	// ลบ Chatbot Blueprint
	DeleteMultiTenantChatbot(ctx context.Context, in *DeleteMultiTenantChatbotRequest, opts ...grpc.CallOption) (*DeleteMultiTenantChatbotResponse, error)
}

type chatbotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatbotServiceClient(cc grpc.ClientConnInterface) ChatbotServiceClient {
	return &chatbotServiceClient{cc}
}

func (c *chatbotServiceClient) CreateMultiTenantChatbot(ctx context.Context, in *CreateMultiTenantChatbotRequest, opts ...grpc.CallOption) (*CreateMultiTenantChatbotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMultiTenantChatbotResponse)
	err := c.cc.Invoke(ctx, ChatbotService_CreateMultiTenantChatbot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) GetMultiTenantChatbot(ctx context.Context, in *GetMultiTenantChatbotRequest, opts ...grpc.CallOption) (*GetMultiTenantChatbotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMultiTenantChatbotResponse)
	err := c.cc.Invoke(ctx, ChatbotService_GetMultiTenantChatbot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) ListMultiTenantChatbots(ctx context.Context, in *ListMultiTenantChatbotsRequest, opts ...grpc.CallOption) (*ListMultiTenantChatbotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMultiTenantChatbotsResponse)
	err := c.cc.Invoke(ctx, ChatbotService_ListMultiTenantChatbots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) UpdateMultiTenantChatbot(ctx context.Context, in *UpdateMultiTenantChatbotRequest, opts ...grpc.CallOption) (*UpdateMultiTenantChatbotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMultiTenantChatbotResponse)
	err := c.cc.Invoke(ctx, ChatbotService_UpdateMultiTenantChatbot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) DeleteMultiTenantChatbot(ctx context.Context, in *DeleteMultiTenantChatbotRequest, opts ...grpc.CallOption) (*DeleteMultiTenantChatbotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMultiTenantChatbotResponse)
	err := c.cc.Invoke(ctx, ChatbotService_DeleteMultiTenantChatbot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatbotServiceServer is the server API for ChatbotService service.
// All implementations must embed UnimplementedChatbotServiceServer
// for forward compatibility.
//
// Service สำหรับจัดการ Chatbot Blueprint / Profile Operations
type ChatbotServiceServer interface {
	// สร้าง Chatbot Blueprint ใหม่
	CreateMultiTenantChatbot(context.Context, *CreateMultiTenantChatbotRequest) (*CreateMultiTenantChatbotResponse, error)
	// ดึงข้อมูล Chatbot Blueprint ตาม ID
	GetMultiTenantChatbot(context.Context, *GetMultiTenantChatbotRequest) (*GetMultiTenantChatbotResponse, error)
	// ดึงรายการ Chatbot Blueprint ทั้งหมดของผู้ใช้ (รองรับ Pagination)
	ListMultiTenantChatbots(context.Context, *ListMultiTenantChatbotsRequest) (*ListMultiTenantChatbotsResponse, error)
	// แก้ไขข้อมูล Chatbot Blueprint (ใช้ FieldMask สำหรับ Partial Update)
	UpdateMultiTenantChatbot(context.Context, *UpdateMultiTenantChatbotRequest) (*UpdateMultiTenantChatbotResponse, error)
	// ลบ Chatbot Blueprint
	DeleteMultiTenantChatbot(context.Context, *DeleteMultiTenantChatbotRequest) (*DeleteMultiTenantChatbotResponse, error)
	mustEmbedUnimplementedChatbotServiceServer()
}

// UnimplementedChatbotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatbotServiceServer struct{}

func (UnimplementedChatbotServiceServer) CreateMultiTenantChatbot(context.Context, *CreateMultiTenantChatbotRequest) (*CreateMultiTenantChatbotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMultiTenantChatbot not implemented")
}
func (UnimplementedChatbotServiceServer) GetMultiTenantChatbot(context.Context, *GetMultiTenantChatbotRequest) (*GetMultiTenantChatbotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMultiTenantChatbot not implemented")
}
func (UnimplementedChatbotServiceServer) ListMultiTenantChatbots(context.Context, *ListMultiTenantChatbotsRequest) (*ListMultiTenantChatbotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMultiTenantChatbots not implemented")
}
func (UnimplementedChatbotServiceServer) UpdateMultiTenantChatbot(context.Context, *UpdateMultiTenantChatbotRequest) (*UpdateMultiTenantChatbotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMultiTenantChatbot not implemented")
}
func (UnimplementedChatbotServiceServer) DeleteMultiTenantChatbot(context.Context, *DeleteMultiTenantChatbotRequest) (*DeleteMultiTenantChatbotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMultiTenantChatbot not implemented")
}
func (UnimplementedChatbotServiceServer) mustEmbedUnimplementedChatbotServiceServer() {}
func (UnimplementedChatbotServiceServer) testEmbeddedByValue()                        {}

// UnsafeChatbotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatbotServiceServer will
// result in compilation errors.
type UnsafeChatbotServiceServer interface {
	mustEmbedUnimplementedChatbotServiceServer()
}

func RegisterChatbotServiceServer(s grpc.ServiceRegistrar, srv ChatbotServiceServer) {
	// If the following call panics, it indicates UnimplementedChatbotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatbotService_ServiceDesc, srv)
}

func _ChatbotService_CreateMultiTenantChatbot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMultiTenantChatbotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).CreateMultiTenantChatbot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_CreateMultiTenantChatbot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).CreateMultiTenantChatbot(ctx, req.(*CreateMultiTenantChatbotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_GetMultiTenantChatbot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultiTenantChatbotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).GetMultiTenantChatbot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_GetMultiTenantChatbot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).GetMultiTenantChatbot(ctx, req.(*GetMultiTenantChatbotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_ListMultiTenantChatbots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMultiTenantChatbotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).ListMultiTenantChatbots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_ListMultiTenantChatbots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).ListMultiTenantChatbots(ctx, req.(*ListMultiTenantChatbotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_UpdateMultiTenantChatbot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMultiTenantChatbotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).UpdateMultiTenantChatbot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_UpdateMultiTenantChatbot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).UpdateMultiTenantChatbot(ctx, req.(*UpdateMultiTenantChatbotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_DeleteMultiTenantChatbot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMultiTenantChatbotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).DeleteMultiTenantChatbot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_DeleteMultiTenantChatbot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).DeleteMultiTenantChatbot(ctx, req.(*DeleteMultiTenantChatbotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatbotService_ServiceDesc is the grpc.ServiceDesc for ChatbotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatbotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatbot.v1.ChatbotService",
	HandlerType: (*ChatbotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMultiTenantChatbot",
			Handler:    _ChatbotService_CreateMultiTenantChatbot_Handler,
		},
		{
			MethodName: "GetMultiTenantChatbot",
			Handler:    _ChatbotService_GetMultiTenantChatbot_Handler,
		},
		{
			MethodName: "ListMultiTenantChatbots",
			Handler:    _ChatbotService_ListMultiTenantChatbots_Handler,
		},
		{
			MethodName: "UpdateMultiTenantChatbot",
			Handler:    _ChatbotService_UpdateMultiTenantChatbot_Handler,
		},
		{
			MethodName: "DeleteMultiTenantChatbot",
			Handler:    _ChatbotService_DeleteMultiTenantChatbot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatbot.proto",
}
