// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: chat_session.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatSessionService_CreateChatSession_FullMethodName = "/chat_session.v1.ChatSessionService/CreateChatSession"
	ChatSessionService_GetChatSession_FullMethodName    = "/chat_session.v1.ChatSessionService/GetChatSession"
	ChatSessionService_ListChatSessions_FullMethodName  = "/chat_session.v1.ChatSessionService/ListChatSessions"
	ChatSessionService_AddChatMessage_FullMethodName    = "/chat_session.v1.ChatSessionService/AddChatMessage"
	ChatSessionService_DeleteChatSession_FullMethodName = "/chat_session.v1.ChatSessionService/DeleteChatSession"
)

// ChatSessionServiceClient is the client API for ChatSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service สำหรับจัดการ Chat Session และ Chat Message
type ChatSessionServiceClient interface {
	// สร้าง Session การสนทนาใหม่
	CreateChatSession(ctx context.Context, in *CreateChatSessionRequest, opts ...grpc.CallOption) (*CreateChatSessionResponse, error)
	// ดึงข้อมูล Session พร้อมประวัติการคุยตาม ID
	GetChatSession(ctx context.Context, in *GetChatSessionRequest, opts ...grpc.CallOption) (*GetChatSessionResponse, error)
	// ดึงรายการ Chat Sessions ของผู้ใช้ (รองรับ Filter ตาม chatbot_id และ Pagination)
	ListChatSessions(ctx context.Context, in *ListChatSessionsRequest, opts ...grpc.CallOption) (*ListChatSessionsResponse, error)
	// บันทึกข้อความใหม่ลงใน Session
	AddChatMessage(ctx context.Context, in *AddChatMessageRequest, opts ...grpc.CallOption) (*AddChatMessageResponse, error)
	// ลบ Chat Session
	DeleteChatSession(ctx context.Context, in *DeleteChatSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type chatSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatSessionServiceClient(cc grpc.ClientConnInterface) ChatSessionServiceClient {
	return &chatSessionServiceClient{cc}
}

func (c *chatSessionServiceClient) CreateChatSession(ctx context.Context, in *CreateChatSessionRequest, opts ...grpc.CallOption) (*CreateChatSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChatSessionResponse)
	err := c.cc.Invoke(ctx, ChatSessionService_CreateChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) GetChatSession(ctx context.Context, in *GetChatSessionRequest, opts ...grpc.CallOption) (*GetChatSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatSessionResponse)
	err := c.cc.Invoke(ctx, ChatSessionService_GetChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) ListChatSessions(ctx context.Context, in *ListChatSessionsRequest, opts ...grpc.CallOption) (*ListChatSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatSessionsResponse)
	err := c.cc.Invoke(ctx, ChatSessionService_ListChatSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) AddChatMessage(ctx context.Context, in *AddChatMessageRequest, opts ...grpc.CallOption) (*AddChatMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddChatMessageResponse)
	err := c.cc.Invoke(ctx, ChatSessionService_AddChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) DeleteChatSession(ctx context.Context, in *DeleteChatSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatSessionService_DeleteChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatSessionServiceServer is the server API for ChatSessionService service.
// All implementations must embed UnimplementedChatSessionServiceServer
// for forward compatibility.
//
// Service สำหรับจัดการ Chat Session และ Chat Message
type ChatSessionServiceServer interface {
	// สร้าง Session การสนทนาใหม่
	CreateChatSession(context.Context, *CreateChatSessionRequest) (*CreateChatSessionResponse, error)
	// ดึงข้อมูล Session พร้อมประวัติการคุยตาม ID
	GetChatSession(context.Context, *GetChatSessionRequest) (*GetChatSessionResponse, error)
	// ดึงรายการ Chat Sessions ของผู้ใช้ (รองรับ Filter ตาม chatbot_id และ Pagination)
	ListChatSessions(context.Context, *ListChatSessionsRequest) (*ListChatSessionsResponse, error)
	// บันทึกข้อความใหม่ลงใน Session
	AddChatMessage(context.Context, *AddChatMessageRequest) (*AddChatMessageResponse, error)
	// ลบ Chat Session
	DeleteChatSession(context.Context, *DeleteChatSessionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedChatSessionServiceServer()
}

// UnimplementedChatSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatSessionServiceServer struct{}

func (UnimplementedChatSessionServiceServer) CreateChatSession(context.Context, *CreateChatSessionRequest) (*CreateChatSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) GetChatSession(context.Context, *GetChatSessionRequest) (*GetChatSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) ListChatSessions(context.Context, *ListChatSessionsRequest) (*ListChatSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChatSessions not implemented")
}
func (UnimplementedChatSessionServiceServer) AddChatMessage(context.Context, *AddChatMessageRequest) (*AddChatMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddChatMessage not implemented")
}
func (UnimplementedChatSessionServiceServer) DeleteChatSession(context.Context, *DeleteChatSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) mustEmbedUnimplementedChatSessionServiceServer() {}
func (UnimplementedChatSessionServiceServer) testEmbeddedByValue()                            {}

// UnsafeChatSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatSessionServiceServer will
// result in compilation errors.
type UnsafeChatSessionServiceServer interface {
	mustEmbedUnimplementedChatSessionServiceServer()
}

func RegisterChatSessionServiceServer(s grpc.ServiceRegistrar, srv ChatSessionServiceServer) {
	// If the following call panics, it indicates UnimplementedChatSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatSessionService_ServiceDesc, srv)
}

func _ChatSessionService_CreateChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).CreateChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_CreateChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).CreateChatSession(ctx, req.(*CreateChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_GetChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).GetChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_GetChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).GetChatSession(ctx, req.(*GetChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_ListChatSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).ListChatSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_ListChatSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).ListChatSessions(ctx, req.(*ListChatSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_AddChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).AddChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_AddChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).AddChatMessage(ctx, req.(*AddChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_DeleteChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).DeleteChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_DeleteChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).DeleteChatSession(ctx, req.(*DeleteChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatSessionService_ServiceDesc is the grpc.ServiceDesc for ChatSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat_session.v1.ChatSessionService",
	HandlerType: (*ChatSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChatSession",
			Handler:    _ChatSessionService_CreateChatSession_Handler,
		},
		{
			MethodName: "GetChatSession",
			Handler:    _ChatSessionService_GetChatSession_Handler,
		},
		{
			MethodName: "ListChatSessions",
			Handler:    _ChatSessionService_ListChatSessions_Handler,
		},
		{
			MethodName: "AddChatMessage",
			Handler:    _ChatSessionService_AddChatMessage_Handler,
		},
		{
			MethodName: "DeleteChatSession",
			Handler:    _ChatSessionService_DeleteChatSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat_session.proto",
}
