// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: chat_session.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// บทบาทของผู้ส่งข้อความ
type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_USER                     MessageRole = 1
	MessageRole_AI                       MessageRole = 2
	MessageRole_SYSTEM                   MessageRole = 3
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "USER",
		2: "AI",
		3: "SYSTEM",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"USER":                     1,
		"AI":                       2,
		"SYSTEM":                   3,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_session_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_chat_session_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{0}
}

// โครงสร้างข้อความสนทนา
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          MessageRole            `protobuf:"varint,1,opt,name=role,proto3,enum=chat_session.v1.MessageRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// โครงสร้างประวัติการสนทนา (Session)
type ChatSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // MongoDB _id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Owner/Tenant ID
	ChatbotId     string                 `protobuf:"bytes,3,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`          // Chatbot ID ที่คุยด้วย
	SessionTitle  string                 `protobuf:"bytes,4,opt,name=session_title,json=sessionTitle,proto3" json:"session_title,omitempty"` // หัวข้อสนทนา
	Messages      []*ChatMessage         `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`                             // รายการข้อความใน Session
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSession) Reset() {
	*x = ChatSession{}
	mi := &file_chat_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSession) ProtoMessage() {}

func (x *ChatSession) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSession.ProtoReflect.Descriptor instead.
func (*ChatSession) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{1}
}

func (x *ChatSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatSession) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *ChatSession) GetSessionTitle() string {
	if x != nil {
		return x.SessionTitle
	}
	return ""
}

func (x *ChatSession) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 1. Create Session
type CreateChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Required
	ChatbotId     string                 `protobuf:"bytes,2,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`          // Required
	SessionTitle  string                 `protobuf:"bytes,3,opt,name=session_title,json=sessionTitle,proto3" json:"session_title,omitempty"` // Optional (ถ้าไม่ส่ง ให้ default เป็น "New Chat")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatSessionRequest) Reset() {
	*x = CreateChatSessionRequest{}
	mi := &file_chat_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionRequest) ProtoMessage() {}

func (x *CreateChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateChatSessionRequest) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *CreateChatSessionRequest) GetSessionTitle() string {
	if x != nil {
		return x.SessionTitle
	}
	return ""
}

type CreateChatSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ChatSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatSessionResponse) Reset() {
	*x = CreateChatSessionResponse{}
	mi := &file_chat_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionResponse) ProtoMessage() {}

func (x *CreateChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChatSessionResponse) GetSession() *ChatSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// 2. Get Session
type GetChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // Session ID (Required)
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID สำหรับ Multi-tenant validation (Required)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatSessionRequest) Reset() {
	*x = GetChatSessionRequest{}
	mi := &file_chat_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatSessionRequest) ProtoMessage() {}

func (x *GetChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatSessionRequest.ProtoReflect.Descriptor instead.
func (*GetChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetChatSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ChatSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatSessionResponse) Reset() {
	*x = GetChatSessionResponse{}
	mi := &file_chat_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatSessionResponse) ProtoMessage() {}

func (x *GetChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatSessionResponse.ProtoReflect.Descriptor instead.
func (*GetChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatSessionResponse) GetSession() *ChatSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// 3. List Sessions
type ListChatSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // Required
	ChatbotId     string                 `protobuf:"bytes,2,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`  // Optional: สำหรับกรองเฉพาะ Chatbot ตัวที่กำหนด
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // Limit (Default เช่น 20)
	PageToken     int32                  `protobuf:"varint,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // Offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsRequest) Reset() {
	*x = ListChatSessionsRequest{}
	mi := &file_chat_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsRequest) ProtoMessage() {}

func (x *ListChatSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListChatSessionsRequest) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{6}
}

func (x *ListChatSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListChatSessionsRequest) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *ListChatSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChatSessionsRequest) GetPageToken() int32 {
	if x != nil {
		return x.PageToken
	}
	return 0
}

type ListChatSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ChatSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsResponse) Reset() {
	*x = ListChatSessionsResponse{}
	mi := &file_chat_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsResponse) ProtoMessage() {}

func (x *ListChatSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListChatSessionsResponse) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatSessionsResponse) GetSessions() []*ChatSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListChatSessionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 4. Add Message
type AddChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Required
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // Required ( Multi-tenant protection )
	Role          MessageRole            `protobuf:"varint,3,opt,name=role,proto3,enum=chat_session.v1.MessageRole" json:"role,omitempty"` // Required (USER, AI, SYSTEM)
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                             // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChatMessageRequest) Reset() {
	*x = AddChatMessageRequest{}
	mi := &file_chat_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatMessageRequest) ProtoMessage() {}

func (x *AddChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatMessageRequest.ProtoReflect.Descriptor instead.
func (*AddChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{8}
}

func (x *AddChatMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddChatMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddChatMessageRequest) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *AddChatMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // ข้อความที่เพิ่งบันทึกสำเร็จ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChatMessageResponse) Reset() {
	*x = AddChatMessageResponse{}
	mi := &file_chat_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatMessageResponse) ProtoMessage() {}

func (x *AddChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatMessageResponse.ProtoReflect.Descriptor instead.
func (*AddChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{9}
}

func (x *AddChatMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// 5. Delete Session
type DeleteChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // Session ID (Required)
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID สำหรับ Multi-tenant validation (Required)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatSessionRequest) Reset() {
	*x = DeleteChatSessionRequest{}
	mi := &file_chat_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatSessionRequest) ProtoMessage() {}

func (x *DeleteChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_session_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteChatSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_chat_session_proto protoreflect.FileDescriptor

const file_chat_session_proto_rawDesc = "" +
	"\n" +
	"\x12chat_session.proto\x12\x0fchat_session.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x94\x01\n" +
	"\vChatMessage\x120\n" +
	"\x04role\x18\x01 \x01(\x0e2\x1c.chat_session.v1.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaa\x02\n" +
	"\vChatSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x03 \x01(\tR\tchatbotId\x12#\n" +
	"\rsession_title\x18\x04 \x01(\tR\fsessionTitle\x128\n" +
	"\bmessages\x18\x05 \x03(\v2\x1c.chat_session.v1.ChatMessageR\bmessages\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"w\n" +
	"\x18CreateChatSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x02 \x01(\tR\tchatbotId\x12#\n" +
	"\rsession_title\x18\x03 \x01(\tR\fsessionTitle\"S\n" +
	"\x19CreateChatSessionResponse\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.chat_session.v1.ChatSessionR\asession\"@\n" +
	"\x15GetChatSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x16GetChatSessionResponse\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.chat_session.v1.ChatSessionR\asession\"\x8d\x01\n" +
	"\x17ListChatSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x02 \x01(\tR\tchatbotId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\x05R\tpageToken\"u\n" +
	"\x18ListChatSessionsResponse\x128\n" +
	"\bsessions\x18\x01 \x03(\v2\x1c.chat_session.v1.ChatSessionR\bsessions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x9b\x01\n" +
	"\x15AddChatMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x120\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1c.chat_session.v1.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"P\n" +
	"\x16AddChatMessageResponse\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.chat_session.v1.ChatMessageR\amessage\"C\n" +
	"\x18DeleteChatSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId*I\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\x06\n" +
	"\x02AI\x10\x02\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x032\x87\x04\n" +
	"\x12ChatSessionService\x12j\n" +
	"\x11CreateChatSession\x12).chat_session.v1.CreateChatSessionRequest\x1a*.chat_session.v1.CreateChatSessionResponse\x12a\n" +
	"\x0eGetChatSession\x12&.chat_session.v1.GetChatSessionRequest\x1a'.chat_session.v1.GetChatSessionResponse\x12g\n" +
	"\x10ListChatSessions\x12(.chat_session.v1.ListChatSessionsRequest\x1a).chat_session.v1.ListChatSessionsResponse\x12a\n" +
	"\x0eAddChatMessage\x12&.chat_session.v1.AddChatMessageRequest\x1a'.chat_session.v1.AddChatMessageResponse\x12V\n" +
	"\x11DeleteChatSession\x12).chat_session.v1.DeleteChatSessionRequest\x1a\x16.google.protobuf.EmptyBAZ?github.com/ballinwza/scraper-dashboard-be/api/proto/v1;grpc_apib\x06proto3"

var (
	file_chat_session_proto_rawDescOnce sync.Once
	file_chat_session_proto_rawDescData []byte
)

func file_chat_session_proto_rawDescGZIP() []byte {
	file_chat_session_proto_rawDescOnce.Do(func() {
		file_chat_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_session_proto_rawDesc), len(file_chat_session_proto_rawDesc)))
	})
	return file_chat_session_proto_rawDescData
}

var file_chat_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_session_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chat_session_proto_goTypes = []any{
	(MessageRole)(0),                  // 0: chat_session.v1.MessageRole
	(*ChatMessage)(nil),               // 1: chat_session.v1.ChatMessage
	(*ChatSession)(nil),               // 2: chat_session.v1.ChatSession
	(*CreateChatSessionRequest)(nil),  // 3: chat_session.v1.CreateChatSessionRequest
	(*CreateChatSessionResponse)(nil), // 4: chat_session.v1.CreateChatSessionResponse
	(*GetChatSessionRequest)(nil),     // 5: chat_session.v1.GetChatSessionRequest
	(*GetChatSessionResponse)(nil),    // 6: chat_session.v1.GetChatSessionResponse
	(*ListChatSessionsRequest)(nil),   // 7: chat_session.v1.ListChatSessionsRequest
	(*ListChatSessionsResponse)(nil),  // 8: chat_session.v1.ListChatSessionsResponse
	(*AddChatMessageRequest)(nil),     // 9: chat_session.v1.AddChatMessageRequest
	(*AddChatMessageResponse)(nil),    // 10: chat_session.v1.AddChatMessageResponse
	(*DeleteChatSessionRequest)(nil),  // 11: chat_session.v1.DeleteChatSessionRequest
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 13: google.protobuf.Empty
}
var file_chat_session_proto_depIdxs = []int32{
	0,  // 0: chat_session.v1.ChatMessage.role:type_name -> chat_session.v1.MessageRole
	12, // 1: chat_session.v1.ChatMessage.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chat_session.v1.ChatSession.messages:type_name -> chat_session.v1.ChatMessage
	12, // 3: chat_session.v1.ChatSession.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: chat_session.v1.ChatSession.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: chat_session.v1.CreateChatSessionResponse.session:type_name -> chat_session.v1.ChatSession
	2,  // 6: chat_session.v1.GetChatSessionResponse.session:type_name -> chat_session.v1.ChatSession
	2,  // 7: chat_session.v1.ListChatSessionsResponse.sessions:type_name -> chat_session.v1.ChatSession
	0,  // 8: chat_session.v1.AddChatMessageRequest.role:type_name -> chat_session.v1.MessageRole
	1,  // 9: chat_session.v1.AddChatMessageResponse.message:type_name -> chat_session.v1.ChatMessage
	3,  // 10: chat_session.v1.ChatSessionService.CreateChatSession:input_type -> chat_session.v1.CreateChatSessionRequest
	5,  // 11: chat_session.v1.ChatSessionService.GetChatSession:input_type -> chat_session.v1.GetChatSessionRequest
	7,  // 12: chat_session.v1.ChatSessionService.ListChatSessions:input_type -> chat_session.v1.ListChatSessionsRequest
	9,  // 13: chat_session.v1.ChatSessionService.AddChatMessage:input_type -> chat_session.v1.AddChatMessageRequest
	11, // 14: chat_session.v1.ChatSessionService.DeleteChatSession:input_type -> chat_session.v1.DeleteChatSessionRequest
	4,  // 15: chat_session.v1.ChatSessionService.CreateChatSession:output_type -> chat_session.v1.CreateChatSessionResponse
	6,  // 16: chat_session.v1.ChatSessionService.GetChatSession:output_type -> chat_session.v1.GetChatSessionResponse
	8,  // 17: chat_session.v1.ChatSessionService.ListChatSessions:output_type -> chat_session.v1.ListChatSessionsResponse
	10, // 18: chat_session.v1.ChatSessionService.AddChatMessage:output_type -> chat_session.v1.AddChatMessageResponse
	13, // 19: chat_session.v1.ChatSessionService.DeleteChatSession:output_type -> google.protobuf.Empty
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chat_session_proto_init() }
func file_chat_session_proto_init() {
	if File_chat_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_session_proto_rawDesc), len(file_chat_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_session_proto_goTypes,
		DependencyIndexes: file_chat_session_proto_depIdxs,
		EnumInfos:         file_chat_session_proto_enumTypes,
		MessageInfos:      file_chat_session_proto_msgTypes,
	}.Build()
	File_chat_session_proto = out.File
	file_chat_session_proto_goTypes = nil
	file_chat_session_proto_depIdxs = nil
}
