// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: chatbot.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message แสดงข้อมูลพิมพ์เขียวของ Chatbot Blueprint
type ChatbotBlueprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Unique Identifier (MongoDB _id)
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // ID ของผู้ใช้งาน/เจ้าของ (Multi-tenant ID)
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                     // ชื่อของ Chatbot
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                       // รายละเอียด/บทบาทของ Chatbot
	SystemPrompt  string                 `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"` // คำสั่งหลักควบคุมนิสัยและกฎเกณฑ์ของ LLM
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // เวลาสร้าง
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // เวลาอัปเดตล่าสุด
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatbotBlueprint) Reset() {
	*x = ChatbotBlueprint{}
	mi := &file_chatbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatbotBlueprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatbotBlueprint) ProtoMessage() {}

func (x *ChatbotBlueprint) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatbotBlueprint.ProtoReflect.Descriptor instead.
func (*ChatbotBlueprint) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{0}
}

func (x *ChatbotBlueprint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatbotBlueprint) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatbotBlueprint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatbotBlueprint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatbotBlueprint) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatbotBlueprint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatbotBlueprint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 1. Create Chatbot
type CreateMultiTenantChatbotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Required: เจ้าของบอท
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // Required: ชื่อบอท
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                       // Optional: คำอธิบาย
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"` // Required: System Instruction สำหรับ LLM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMultiTenantChatbotRequest) Reset() {
	*x = CreateMultiTenantChatbotRequest{}
	mi := &file_chatbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMultiTenantChatbotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMultiTenantChatbotRequest) ProtoMessage() {}

func (x *CreateMultiTenantChatbotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMultiTenantChatbotRequest.ProtoReflect.Descriptor instead.
func (*CreateMultiTenantChatbotRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMultiTenantChatbotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMultiTenantChatbotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMultiTenantChatbotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMultiTenantChatbotRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

type CreateMultiTenantChatbotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chatbot       *ChatbotBlueprint      `protobuf:"bytes,1,opt,name=chatbot,proto3" json:"chatbot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMultiTenantChatbotResponse) Reset() {
	*x = CreateMultiTenantChatbotResponse{}
	mi := &file_chatbot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMultiTenantChatbotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMultiTenantChatbotResponse) ProtoMessage() {}

func (x *CreateMultiTenantChatbotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMultiTenantChatbotResponse.ProtoReflect.Descriptor instead.
func (*CreateMultiTenantChatbotResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMultiTenantChatbotResponse) GetChatbot() *ChatbotBlueprint {
	if x != nil {
		return x.Chatbot
	}
	return nil
}

// 2. Get Chatbot
type GetMultiTenantChatbotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // Required: Chatbot ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required: User ID สำหรับตรวจสิทธิ์ (Multi-tenant Security)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultiTenantChatbotRequest) Reset() {
	*x = GetMultiTenantChatbotRequest{}
	mi := &file_chatbot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultiTenantChatbotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultiTenantChatbotRequest) ProtoMessage() {}

func (x *GetMultiTenantChatbotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultiTenantChatbotRequest.ProtoReflect.Descriptor instead.
func (*GetMultiTenantChatbotRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{3}
}

func (x *GetMultiTenantChatbotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMultiTenantChatbotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMultiTenantChatbotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chatbot       *ChatbotBlueprint      `protobuf:"bytes,1,opt,name=chatbot,proto3" json:"chatbot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultiTenantChatbotResponse) Reset() {
	*x = GetMultiTenantChatbotResponse{}
	mi := &file_chatbot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultiTenantChatbotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultiTenantChatbotResponse) ProtoMessage() {}

func (x *GetMultiTenantChatbotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultiTenantChatbotResponse.ProtoReflect.Descriptor instead.
func (*GetMultiTenantChatbotResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{4}
}

func (x *GetMultiTenantChatbotResponse) GetChatbot() *ChatbotBlueprint {
	if x != nil {
		return x.Chatbot
	}
	return nil
}

// 3. List Chatbots
type ListMultiTenantChatbotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // Required: User ID ที่ต้องการดึงรายการบอท
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // จำนวนรายการต่อหน้า (Default เช่น 10 หรือ 20)
	PageToken     int32                  `protobuf:"varint,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // Page token / Offset สำหรับ Pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMultiTenantChatbotsRequest) Reset() {
	*x = ListMultiTenantChatbotsRequest{}
	mi := &file_chatbot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMultiTenantChatbotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMultiTenantChatbotsRequest) ProtoMessage() {}

func (x *ListMultiTenantChatbotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMultiTenantChatbotsRequest.ProtoReflect.Descriptor instead.
func (*ListMultiTenantChatbotsRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{5}
}

func (x *ListMultiTenantChatbotsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMultiTenantChatbotsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMultiTenantChatbotsRequest) GetPageToken() int32 {
	if x != nil {
		return x.PageToken
	}
	return 0
}

type ListMultiTenantChatbotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chatbots      []*ChatbotBlueprint    `protobuf:"bytes,1,rep,name=chatbots,proto3" json:"chatbots,omitempty"`
	NextPageToken int32                  `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // Offset ของหน้าถัดไป (ถ้าเป็น 0 แปลว่าหมดแล้ว)
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`            // จำนวนรายการทั้งหมดของผู้ใช้งานนี้
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMultiTenantChatbotsResponse) Reset() {
	*x = ListMultiTenantChatbotsResponse{}
	mi := &file_chatbot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMultiTenantChatbotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMultiTenantChatbotsResponse) ProtoMessage() {}

func (x *ListMultiTenantChatbotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMultiTenantChatbotsResponse.ProtoReflect.Descriptor instead.
func (*ListMultiTenantChatbotsResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{6}
}

func (x *ListMultiTenantChatbotsResponse) GetChatbots() []*ChatbotBlueprint {
	if x != nil {
		return x.Chatbots
	}
	return nil
}

func (x *ListMultiTenantChatbotsResponse) GetNextPageToken() int32 {
	if x != nil {
		return x.NextPageToken
	}
	return 0
}

func (x *ListMultiTenantChatbotsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 4. Update Chatbot
type UpdateMultiTenantChatbotRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Required: Chatbot ID ที่ต้องการแก้
	UserId       string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Required: User ID สำหรับตรวจสิทธิ์
	Name         string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                     // Optional: ชื่อใหม่
	Description  string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                       // Optional: รายละเอียดใหม่
	SystemPrompt string                 `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"` // Optional: System Prompt ใหม่
	// FieldMask ระบุ field ที่ต้องการอัปเดต (เช่น "name,system_prompt")
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMultiTenantChatbotRequest) Reset() {
	*x = UpdateMultiTenantChatbotRequest{}
	mi := &file_chatbot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMultiTenantChatbotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMultiTenantChatbotRequest) ProtoMessage() {}

func (x *UpdateMultiTenantChatbotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMultiTenantChatbotRequest.ProtoReflect.Descriptor instead.
func (*UpdateMultiTenantChatbotRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMultiTenantChatbotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMultiTenantChatbotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMultiTenantChatbotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMultiTenantChatbotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMultiTenantChatbotRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdateMultiTenantChatbotRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateMultiTenantChatbotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chatbot       *ChatbotBlueprint      `protobuf:"bytes,1,opt,name=chatbot,proto3" json:"chatbot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMultiTenantChatbotResponse) Reset() {
	*x = UpdateMultiTenantChatbotResponse{}
	mi := &file_chatbot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMultiTenantChatbotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMultiTenantChatbotResponse) ProtoMessage() {}

func (x *UpdateMultiTenantChatbotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMultiTenantChatbotResponse.ProtoReflect.Descriptor instead.
func (*UpdateMultiTenantChatbotResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMultiTenantChatbotResponse) GetChatbot() *ChatbotBlueprint {
	if x != nil {
		return x.Chatbot
	}
	return nil
}

// 5. Delete Chatbot
type DeleteMultiTenantChatbotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // Required: Chatbot ID ที่ต้องการลบ
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required: User ID สำหรับตรวจสิทธิ์
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMultiTenantChatbotRequest) Reset() {
	*x = DeleteMultiTenantChatbotRequest{}
	mi := &file_chatbot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMultiTenantChatbotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMultiTenantChatbotRequest) ProtoMessage() {}

func (x *DeleteMultiTenantChatbotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMultiTenantChatbotRequest.ProtoReflect.Descriptor instead.
func (*DeleteMultiTenantChatbotRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMultiTenantChatbotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteMultiTenantChatbotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteMultiTenantChatbotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // ผลลัพธ์การลบ (true/false)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // ข้อความแจ้งสถานะ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMultiTenantChatbotResponse) Reset() {
	*x = DeleteMultiTenantChatbotResponse{}
	mi := &file_chatbot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMultiTenantChatbotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMultiTenantChatbotResponse) ProtoMessage() {}

func (x *DeleteMultiTenantChatbotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMultiTenantChatbotResponse.ProtoReflect.Descriptor instead.
func (*DeleteMultiTenantChatbotResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMultiTenantChatbotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMultiTenantChatbotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chatbot_proto protoreflect.FileDescriptor

const file_chatbot_proto_rawDesc = "" +
	"\n" +
	"\rchatbot.proto\x12\n" +
	"chatbot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\x8c\x02\n" +
	"\x10ChatbotBlueprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x95\x01\n" +
	"\x1fCreateMultiTenantChatbotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\"Z\n" +
	" CreateMultiTenantChatbotResponse\x126\n" +
	"\achatbot\x18\x01 \x01(\v2\x1c.chatbot.v1.ChatbotBlueprintR\achatbot\"G\n" +
	"\x1cGetMultiTenantChatbotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"W\n" +
	"\x1dGetMultiTenantChatbotResponse\x126\n" +
	"\achatbot\x18\x01 \x01(\v2\x1c.chatbot.v1.ChatbotBlueprintR\achatbot\"u\n" +
	"\x1eListMultiTenantChatbotsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\x05R\tpageToken\"\xa4\x01\n" +
	"\x1fListMultiTenantChatbotsResponse\x128\n" +
	"\bchatbots\x18\x01 \x03(\v2\x1c.chatbot.v1.ChatbotBlueprintR\bchatbots\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\x05R\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xe2\x01\n" +
	"\x1fUpdateMultiTenantChatbotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12;\n" +
	"\vupdate_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"Z\n" +
	" UpdateMultiTenantChatbotResponse\x126\n" +
	"\achatbot\x18\x01 \x01(\v2\x1c.chatbot.v1.ChatbotBlueprintR\achatbot\"J\n" +
	"\x1fDeleteMultiTenantChatbotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"V\n" +
	" DeleteMultiTenantChatbotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd7\x04\n" +
	"\x0eChatbotService\x12u\n" +
	"\x18CreateMultiTenantChatbot\x12+.chatbot.v1.CreateMultiTenantChatbotRequest\x1a,.chatbot.v1.CreateMultiTenantChatbotResponse\x12l\n" +
	"\x15GetMultiTenantChatbot\x12(.chatbot.v1.GetMultiTenantChatbotRequest\x1a).chatbot.v1.GetMultiTenantChatbotResponse\x12r\n" +
	"\x17ListMultiTenantChatbots\x12*.chatbot.v1.ListMultiTenantChatbotsRequest\x1a+.chatbot.v1.ListMultiTenantChatbotsResponse\x12u\n" +
	"\x18UpdateMultiTenantChatbot\x12+.chatbot.v1.UpdateMultiTenantChatbotRequest\x1a,.chatbot.v1.UpdateMultiTenantChatbotResponse\x12u\n" +
	"\x18DeleteMultiTenantChatbot\x12+.chatbot.v1.DeleteMultiTenantChatbotRequest\x1a,.chatbot.v1.DeleteMultiTenantChatbotResponseBAZ?github.com/ballinwza/scraper-dashboard-be/api/proto/v1;grpc_apib\x06proto3"

var (
	file_chatbot_proto_rawDescOnce sync.Once
	file_chatbot_proto_rawDescData []byte
)

func file_chatbot_proto_rawDescGZIP() []byte {
	file_chatbot_proto_rawDescOnce.Do(func() {
		file_chatbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatbot_proto_rawDesc), len(file_chatbot_proto_rawDesc)))
	})
	return file_chatbot_proto_rawDescData
}

var file_chatbot_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chatbot_proto_goTypes = []any{
	(*ChatbotBlueprint)(nil),                 // 0: chatbot.v1.ChatbotBlueprint
	(*CreateMultiTenantChatbotRequest)(nil),  // 1: chatbot.v1.CreateMultiTenantChatbotRequest
	(*CreateMultiTenantChatbotResponse)(nil), // 2: chatbot.v1.CreateMultiTenantChatbotResponse
	(*GetMultiTenantChatbotRequest)(nil),     // 3: chatbot.v1.GetMultiTenantChatbotRequest
	(*GetMultiTenantChatbotResponse)(nil),    // 4: chatbot.v1.GetMultiTenantChatbotResponse
	(*ListMultiTenantChatbotsRequest)(nil),   // 5: chatbot.v1.ListMultiTenantChatbotsRequest
	(*ListMultiTenantChatbotsResponse)(nil),  // 6: chatbot.v1.ListMultiTenantChatbotsResponse
	(*UpdateMultiTenantChatbotRequest)(nil),  // 7: chatbot.v1.UpdateMultiTenantChatbotRequest
	(*UpdateMultiTenantChatbotResponse)(nil), // 8: chatbot.v1.UpdateMultiTenantChatbotResponse
	(*DeleteMultiTenantChatbotRequest)(nil),  // 9: chatbot.v1.DeleteMultiTenantChatbotRequest
	(*DeleteMultiTenantChatbotResponse)(nil), // 10: chatbot.v1.DeleteMultiTenantChatbotResponse
	(*timestamppb.Timestamp)(nil),            // 11: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),            // 12: google.protobuf.FieldMask
}
var file_chatbot_proto_depIdxs = []int32{
	11, // 0: chatbot.v1.ChatbotBlueprint.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: chatbot.v1.ChatbotBlueprint.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: chatbot.v1.CreateMultiTenantChatbotResponse.chatbot:type_name -> chatbot.v1.ChatbotBlueprint
	0,  // 3: chatbot.v1.GetMultiTenantChatbotResponse.chatbot:type_name -> chatbot.v1.ChatbotBlueprint
	0,  // 4: chatbot.v1.ListMultiTenantChatbotsResponse.chatbots:type_name -> chatbot.v1.ChatbotBlueprint
	12, // 5: chatbot.v1.UpdateMultiTenantChatbotRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 6: chatbot.v1.UpdateMultiTenantChatbotResponse.chatbot:type_name -> chatbot.v1.ChatbotBlueprint
	1,  // 7: chatbot.v1.ChatbotService.CreateMultiTenantChatbot:input_type -> chatbot.v1.CreateMultiTenantChatbotRequest
	3,  // 8: chatbot.v1.ChatbotService.GetMultiTenantChatbot:input_type -> chatbot.v1.GetMultiTenantChatbotRequest
	5,  // 9: chatbot.v1.ChatbotService.ListMultiTenantChatbots:input_type -> chatbot.v1.ListMultiTenantChatbotsRequest
	7,  // 10: chatbot.v1.ChatbotService.UpdateMultiTenantChatbot:input_type -> chatbot.v1.UpdateMultiTenantChatbotRequest
	9,  // 11: chatbot.v1.ChatbotService.DeleteMultiTenantChatbot:input_type -> chatbot.v1.DeleteMultiTenantChatbotRequest
	2,  // 12: chatbot.v1.ChatbotService.CreateMultiTenantChatbot:output_type -> chatbot.v1.CreateMultiTenantChatbotResponse
	4,  // 13: chatbot.v1.ChatbotService.GetMultiTenantChatbot:output_type -> chatbot.v1.GetMultiTenantChatbotResponse
	6,  // 14: chatbot.v1.ChatbotService.ListMultiTenantChatbots:output_type -> chatbot.v1.ListMultiTenantChatbotsResponse
	8,  // 15: chatbot.v1.ChatbotService.UpdateMultiTenantChatbot:output_type -> chatbot.v1.UpdateMultiTenantChatbotResponse
	10, // 16: chatbot.v1.ChatbotService.DeleteMultiTenantChatbot:output_type -> chatbot.v1.DeleteMultiTenantChatbotResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chatbot_proto_init() }
func file_chatbot_proto_init() {
	if File_chatbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatbot_proto_rawDesc), len(file_chatbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatbot_proto_goTypes,
		DependencyIndexes: file_chatbot_proto_depIdxs,
		MessageInfos:      file_chatbot_proto_msgTypes,
	}.Build()
	File_chatbot_proto = out.File
	file_chatbot_proto_goTypes = nil
	file_chatbot_proto_depIdxs = nil
}
