// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: knowledge_file.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeFileService_CreateKnowledgeFile_FullMethodName = "/knowledge_file.v1.KnowledgeFileService/CreateKnowledgeFile"
	KnowledgeFileService_GetKnowledgeFile_FullMethodName    = "/knowledge_file.v1.KnowledgeFileService/GetKnowledgeFile"
	KnowledgeFileService_ListKnowledgeFiles_FullMethodName  = "/knowledge_file.v1.KnowledgeFileService/ListKnowledgeFiles"
	KnowledgeFileService_DeleteKnowledgeFile_FullMethodName = "/knowledge_file.v1.KnowledgeFileService/DeleteKnowledgeFile"
)

// KnowledgeFileServiceClient is the client API for KnowledgeFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeFileServiceClient interface {
	// ประมวลผลและสร้าง Ingestion เอกสารเข้า Vector DB
	CreateKnowledgeFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileStreamRequest, UploadFileStreamResponse], error)
	// ดึงข้อมูลเอกสารตาม file_id
	GetKnowledgeFile(ctx context.Context, in *GetKnowledgeFileRequest, opts ...grpc.CallOption) (*GetKnowledgeFileResponse, error)
	// ดึงรายการเอกสารทั้งหมดของ Chatbot
	ListKnowledgeFiles(ctx context.Context, in *ListKnowledgeFilesRequest, opts ...grpc.CallOption) (*ListKnowledgeFilesResponse, error)
	// ลบเอกสารออกจาก MongoDB และ Vector DB
	DeleteKnowledgeFile(ctx context.Context, in *DeleteKnowledgeFileRequest, opts ...grpc.CallOption) (*DeleteKnowledgeFileResponse, error)
}

type knowledgeFileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeFileServiceClient(cc grpc.ClientConnInterface) KnowledgeFileServiceClient {
	return &knowledgeFileServiceClient{cc}
}

func (c *knowledgeFileServiceClient) CreateKnowledgeFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileStreamRequest, UploadFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KnowledgeFileService_ServiceDesc.Streams[0], KnowledgeFileService_CreateKnowledgeFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFileStreamRequest, UploadFileStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KnowledgeFileService_CreateKnowledgeFileClient = grpc.ClientStreamingClient[UploadFileStreamRequest, UploadFileStreamResponse]

func (c *knowledgeFileServiceClient) GetKnowledgeFile(ctx context.Context, in *GetKnowledgeFileRequest, opts ...grpc.CallOption) (*GetKnowledgeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKnowledgeFileResponse)
	err := c.cc.Invoke(ctx, KnowledgeFileService_GetKnowledgeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeFileServiceClient) ListKnowledgeFiles(ctx context.Context, in *ListKnowledgeFilesRequest, opts ...grpc.CallOption) (*ListKnowledgeFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnowledgeFilesResponse)
	err := c.cc.Invoke(ctx, KnowledgeFileService_ListKnowledgeFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeFileServiceClient) DeleteKnowledgeFile(ctx context.Context, in *DeleteKnowledgeFileRequest, opts ...grpc.CallOption) (*DeleteKnowledgeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKnowledgeFileResponse)
	err := c.cc.Invoke(ctx, KnowledgeFileService_DeleteKnowledgeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeFileServiceServer is the server API for KnowledgeFileService service.
// All implementations must embed UnimplementedKnowledgeFileServiceServer
// for forward compatibility.
type KnowledgeFileServiceServer interface {
	// ประมวลผลและสร้าง Ingestion เอกสารเข้า Vector DB
	CreateKnowledgeFile(grpc.ClientStreamingServer[UploadFileStreamRequest, UploadFileStreamResponse]) error
	// ดึงข้อมูลเอกสารตาม file_id
	GetKnowledgeFile(context.Context, *GetKnowledgeFileRequest) (*GetKnowledgeFileResponse, error)
	// ดึงรายการเอกสารทั้งหมดของ Chatbot
	ListKnowledgeFiles(context.Context, *ListKnowledgeFilesRequest) (*ListKnowledgeFilesResponse, error)
	// ลบเอกสารออกจาก MongoDB และ Vector DB
	DeleteKnowledgeFile(context.Context, *DeleteKnowledgeFileRequest) (*DeleteKnowledgeFileResponse, error)
	mustEmbedUnimplementedKnowledgeFileServiceServer()
}

// UnimplementedKnowledgeFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeFileServiceServer struct{}

func (UnimplementedKnowledgeFileServiceServer) CreateKnowledgeFile(grpc.ClientStreamingServer[UploadFileStreamRequest, UploadFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateKnowledgeFile not implemented")
}
func (UnimplementedKnowledgeFileServiceServer) GetKnowledgeFile(context.Context, *GetKnowledgeFileRequest) (*GetKnowledgeFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnowledgeFile not implemented")
}
func (UnimplementedKnowledgeFileServiceServer) ListKnowledgeFiles(context.Context, *ListKnowledgeFilesRequest) (*ListKnowledgeFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnowledgeFiles not implemented")
}
func (UnimplementedKnowledgeFileServiceServer) DeleteKnowledgeFile(context.Context, *DeleteKnowledgeFileRequest) (*DeleteKnowledgeFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKnowledgeFile not implemented")
}
func (UnimplementedKnowledgeFileServiceServer) mustEmbedUnimplementedKnowledgeFileServiceServer() {}
func (UnimplementedKnowledgeFileServiceServer) testEmbeddedByValue()                              {}

// UnsafeKnowledgeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeFileServiceServer will
// result in compilation errors.
type UnsafeKnowledgeFileServiceServer interface {
	mustEmbedUnimplementedKnowledgeFileServiceServer()
}

func RegisterKnowledgeFileServiceServer(s grpc.ServiceRegistrar, srv KnowledgeFileServiceServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeFileService_ServiceDesc, srv)
}

func _KnowledgeFileService_CreateKnowledgeFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KnowledgeFileServiceServer).CreateKnowledgeFile(&grpc.GenericServerStream[UploadFileStreamRequest, UploadFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KnowledgeFileService_CreateKnowledgeFileServer = grpc.ClientStreamingServer[UploadFileStreamRequest, UploadFileStreamResponse]

func _KnowledgeFileService_GetKnowledgeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeFileServiceServer).GetKnowledgeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeFileService_GetKnowledgeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeFileServiceServer).GetKnowledgeFile(ctx, req.(*GetKnowledgeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeFileService_ListKnowledgeFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnowledgeFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeFileServiceServer).ListKnowledgeFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeFileService_ListKnowledgeFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeFileServiceServer).ListKnowledgeFiles(ctx, req.(*ListKnowledgeFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeFileService_DeleteKnowledgeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeFileServiceServer).DeleteKnowledgeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeFileService_DeleteKnowledgeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeFileServiceServer).DeleteKnowledgeFile(ctx, req.(*DeleteKnowledgeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeFileService_ServiceDesc is the grpc.ServiceDesc for KnowledgeFileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeFileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge_file.v1.KnowledgeFileService",
	HandlerType: (*KnowledgeFileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKnowledgeFile",
			Handler:    _KnowledgeFileService_GetKnowledgeFile_Handler,
		},
		{
			MethodName: "ListKnowledgeFiles",
			Handler:    _KnowledgeFileService_ListKnowledgeFiles_Handler,
		},
		{
			MethodName: "DeleteKnowledgeFile",
			Handler:    _KnowledgeFileService_DeleteKnowledgeFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateKnowledgeFile",
			Handler:       _KnowledgeFileService_CreateKnowledgeFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "knowledge_file.proto",
}
