// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: knowledge_file.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum แสดงสถานะการประมวลผลของไฟล์
type FileStatus int32

const (
	FileStatus_PENDING   FileStatus = 0
	FileStatus_COMPLETED FileStatus = 1
	FileStatus_FAILED    FileStatus = 2
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "PENDING",
		1: "COMPLETED",
		2: "FAILED",
	}
	FileStatus_value = map[string]int32{
		"PENDING":   0,
		"COMPLETED": 1,
		"FAILED":    2,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledge_file_proto_enumTypes[0].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_knowledge_file_proto_enumTypes[0]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{0}
}

// Struct แสดงข้อมูล Chunk ของเอกสาร
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorId      string                 `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TextContent   string                 `protobuf:"bytes,3,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	PageNumber    int32                  `protobuf:"varint,4,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	TokenCount    int32                  `protobuf:"varint,5,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_knowledge_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *Chunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Chunk) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *Chunk) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Chunk) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

// Message แสดงข้อมูล KnowledgeFile Entity
type KnowledgeFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatbotId     string                 `protobuf:"bytes,3,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,6,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	Status        FileStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=knowledge_file.v1.FileStatus" json:"status,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,8,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Chunks        []*Chunk               `protobuf:"bytes,9,rep,name=chunks,proto3" json:"chunks,omitempty"`
	TotalPage     int32                  `protobuf:"varint,10,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	TextContent   *string                `protobuf:"bytes,11,opt,name=text_content,json=textContent,proto3,oneof" json:"text_content,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeFile) Reset() {
	*x = KnowledgeFile{}
	mi := &file_knowledge_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeFile) ProtoMessage() {}

func (x *KnowledgeFile) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeFile.ProtoReflect.Descriptor instead.
func (*KnowledgeFile) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{1}
}

func (x *KnowledgeFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeFile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KnowledgeFile) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *KnowledgeFile) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *KnowledgeFile) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *KnowledgeFile) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *KnowledgeFile) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_PENDING
}

func (x *KnowledgeFile) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *KnowledgeFile) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *KnowledgeFile) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *KnowledgeFile) GetTextContent() string {
	if x != nil && x.TextContent != nil {
		return *x.TextContent
	}
	return ""
}

func (x *KnowledgeFile) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *KnowledgeFile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeFile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatbotId     string                 `protobuf:"bytes,2,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_knowledge_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileMetadata) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadFileStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFileStreamRequest_Metadata
	//	*UploadFileStreamRequest_ChunkData
	Payload       isUploadFileStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileStreamRequest) Reset() {
	*x = UploadFileStreamRequest{}
	mi := &file_knowledge_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileStreamRequest) ProtoMessage() {}

func (x *UploadFileStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileStreamRequest.ProtoReflect.Descriptor instead.
func (*UploadFileStreamRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileStreamRequest) GetPayload() isUploadFileStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFileStreamRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileStreamRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileStreamRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileStreamRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadFileStreamRequest_Payload interface {
	isUploadFileStreamRequest_Payload()
}

type UploadFileStreamRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadFileStreamRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadFileStreamRequest_Metadata) isUploadFileStreamRequest_Payload() {}

func (*UploadFileStreamRequest_ChunkData) isUploadFileStreamRequest_Payload() {}

type UploadFileStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Status        FileStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=knowledge_file.v1.FileStatus" json:"status,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileStreamResponse) Reset() {
	*x = UploadFileStreamResponse{}
	mi := &file_knowledge_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileStreamResponse) ProtoMessage() {}

func (x *UploadFileStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileStreamResponse.ProtoReflect.Descriptor instead.
func (*UploadFileStreamResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFileStreamResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadFileStreamResponse) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_PENDING
}

func (x *UploadFileStreamResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadFileStreamResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadFileStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileStreamResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetKnowledgeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeFileRequest) Reset() {
	*x = GetKnowledgeFileRequest{}
	mi := &file_knowledge_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeFileRequest) ProtoMessage() {}

func (x *GetKnowledgeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeFileRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeFileRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{5}
}

func (x *GetKnowledgeFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetKnowledgeFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetKnowledgeFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *KnowledgeFile         `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeFileResponse) Reset() {
	*x = GetKnowledgeFileResponse{}
	mi := &file_knowledge_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeFileResponse) ProtoMessage() {}

func (x *GetKnowledgeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeFileResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeFileResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetKnowledgeFileResponse) GetFile() *KnowledgeFile {
	if x != nil {
		return x.File
	}
	return nil
}

type ListKnowledgeFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatbotId     string                 `protobuf:"bytes,2,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeFilesRequest) Reset() {
	*x = ListKnowledgeFilesRequest{}
	mi := &file_knowledge_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeFilesRequest) ProtoMessage() {}

func (x *ListKnowledgeFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeFilesRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeFilesRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{7}
}

func (x *ListKnowledgeFilesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListKnowledgeFilesRequest) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *ListKnowledgeFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListKnowledgeFilesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListKnowledgeFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*KnowledgeFile       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeFilesResponse) Reset() {
	*x = ListKnowledgeFilesResponse{}
	mi := &file_knowledge_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeFilesResponse) ProtoMessage() {}

func (x *ListKnowledgeFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeFilesResponse.ProtoReflect.Descriptor instead.
func (*ListKnowledgeFilesResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{8}
}

func (x *ListKnowledgeFilesResponse) GetFiles() []*KnowledgeFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListKnowledgeFilesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DeleteKnowledgeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatbotId     string                 `protobuf:"bytes,1,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeFileRequest) Reset() {
	*x = DeleteKnowledgeFileRequest{}
	mi := &file_knowledge_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeFileRequest) ProtoMessage() {}

func (x *DeleteKnowledgeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeFileRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteKnowledgeFileRequest) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *DeleteKnowledgeFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteKnowledgeFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeFileResponse) Reset() {
	*x = DeleteKnowledgeFileResponse{}
	mi := &file_knowledge_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeFileResponse) ProtoMessage() {}

func (x *DeleteKnowledgeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeFileResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_file_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteKnowledgeFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteKnowledgeFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_knowledge_file_proto protoreflect.FileDescriptor

const file_knowledge_file_proto_rawDesc = "" +
	"\n" +
	"\x14knowledge_file.proto\x12\x11knowledge_file.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\x05Chunk\x12\x1b\n" +
	"\tvector_id\x18\x01 \x01(\tR\bvectorId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftext_content\x18\x03 \x01(\tR\vtextContent\x12\x1f\n" +
	"\vpage_number\x18\x04 \x01(\x05R\n" +
	"pageNumber\x12\x1f\n" +
	"\vtoken_count\x18\x05 \x01(\x05R\n" +
	"tokenCount\"\xce\x04\n" +
	"\rKnowledgeFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x03 \x01(\tR\tchatbotId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12&\n" +
	"\x0ffile_size_bytes\x18\x06 \x01(\x03R\rfileSizeBytes\x125\n" +
	"\x06status\x18\a \x01(\x0e2\x1d.knowledge_file.v1.FileStatusR\x06status\x12!\n" +
	"\ftotal_chunks\x18\b \x01(\x05R\vtotalChunks\x120\n" +
	"\x06chunks\x18\t \x03(\v2\x18.knowledge_file.v1.ChunkR\x06chunks\x12\x1d\n" +
	"\n" +
	"total_page\x18\n" +
	" \x01(\x05R\ttotalPage\x12&\n" +
	"\ftext_content\x18\v \x01(\tH\x00R\vtextContent\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\f \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0f\n" +
	"\r_text_contentB\x10\n" +
	"\x0e_error_message\"\x7f\n" +
	"\fFileMetadata\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x02 \x01(\tR\tchatbotId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\"\x84\x01\n" +
	"\x17UploadFileStreamRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.knowledge_file.v1.FileMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"\x83\x02\n" +
	"\x18UploadFileStreamResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.knowledge_file.v1.FileStatusR\x06status\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"B\n" +
	"\x17GetKnowledgeFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x18GetKnowledgeFileResponse\x124\n" +
	"\x04file\x18\x01 \x01(\v2 .knowledge_file.v1.KnowledgeFileR\x04file\"\x81\x01\n" +
	"\x19ListKnowledgeFilesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x02 \x01(\tR\tchatbotId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"u\n" +
	"\x1aListKnowledgeFilesResponse\x126\n" +
	"\x05files\x18\x01 \x03(\v2 .knowledge_file.v1.KnowledgeFileR\x05files\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"T\n" +
	"\x1aDeleteKnowledgeFileRequest\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x01 \x01(\tR\tchatbotId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Q\n" +
	"\x1bDeleteKnowledgeFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*4\n" +
	"\n" +
	"FileStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x022\xde\x03\n" +
	"\x14KnowledgeFileService\x12p\n" +
	"\x13CreateKnowledgeFile\x12*.knowledge_file.v1.UploadFileStreamRequest\x1a+.knowledge_file.v1.UploadFileStreamResponse(\x01\x12k\n" +
	"\x10GetKnowledgeFile\x12*.knowledge_file.v1.GetKnowledgeFileRequest\x1a+.knowledge_file.v1.GetKnowledgeFileResponse\x12q\n" +
	"\x12ListKnowledgeFiles\x12,.knowledge_file.v1.ListKnowledgeFilesRequest\x1a-.knowledge_file.v1.ListKnowledgeFilesResponse\x12t\n" +
	"\x13DeleteKnowledgeFile\x12-.knowledge_file.v1.DeleteKnowledgeFileRequest\x1a..knowledge_file.v1.DeleteKnowledgeFileResponseBAZ?github.com/ballinwza/scraper-dashboard-be/api/proto/v1;grpc_apib\x06proto3"

var (
	file_knowledge_file_proto_rawDescOnce sync.Once
	file_knowledge_file_proto_rawDescData []byte
)

func file_knowledge_file_proto_rawDescGZIP() []byte {
	file_knowledge_file_proto_rawDescOnce.Do(func() {
		file_knowledge_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledge_file_proto_rawDesc), len(file_knowledge_file_proto_rawDesc)))
	})
	return file_knowledge_file_proto_rawDescData
}

var file_knowledge_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_knowledge_file_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_knowledge_file_proto_goTypes = []any{
	(FileStatus)(0),                     // 0: knowledge_file.v1.FileStatus
	(*Chunk)(nil),                       // 1: knowledge_file.v1.Chunk
	(*KnowledgeFile)(nil),               // 2: knowledge_file.v1.KnowledgeFile
	(*FileMetadata)(nil),                // 3: knowledge_file.v1.FileMetadata
	(*UploadFileStreamRequest)(nil),     // 4: knowledge_file.v1.UploadFileStreamRequest
	(*UploadFileStreamResponse)(nil),    // 5: knowledge_file.v1.UploadFileStreamResponse
	(*GetKnowledgeFileRequest)(nil),     // 6: knowledge_file.v1.GetKnowledgeFileRequest
	(*GetKnowledgeFileResponse)(nil),    // 7: knowledge_file.v1.GetKnowledgeFileResponse
	(*ListKnowledgeFilesRequest)(nil),   // 8: knowledge_file.v1.ListKnowledgeFilesRequest
	(*ListKnowledgeFilesResponse)(nil),  // 9: knowledge_file.v1.ListKnowledgeFilesResponse
	(*DeleteKnowledgeFileRequest)(nil),  // 10: knowledge_file.v1.DeleteKnowledgeFileRequest
	(*DeleteKnowledgeFileResponse)(nil), // 11: knowledge_file.v1.DeleteKnowledgeFileResponse
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_knowledge_file_proto_depIdxs = []int32{
	0,  // 0: knowledge_file.v1.KnowledgeFile.status:type_name -> knowledge_file.v1.FileStatus
	1,  // 1: knowledge_file.v1.KnowledgeFile.chunks:type_name -> knowledge_file.v1.Chunk
	12, // 2: knowledge_file.v1.KnowledgeFile.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: knowledge_file.v1.KnowledgeFile.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 4: knowledge_file.v1.UploadFileStreamRequest.metadata:type_name -> knowledge_file.v1.FileMetadata
	0,  // 5: knowledge_file.v1.UploadFileStreamResponse.status:type_name -> knowledge_file.v1.FileStatus
	12, // 6: knowledge_file.v1.UploadFileStreamResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 7: knowledge_file.v1.GetKnowledgeFileResponse.file:type_name -> knowledge_file.v1.KnowledgeFile
	2,  // 8: knowledge_file.v1.ListKnowledgeFilesResponse.files:type_name -> knowledge_file.v1.KnowledgeFile
	4,  // 9: knowledge_file.v1.KnowledgeFileService.CreateKnowledgeFile:input_type -> knowledge_file.v1.UploadFileStreamRequest
	6,  // 10: knowledge_file.v1.KnowledgeFileService.GetKnowledgeFile:input_type -> knowledge_file.v1.GetKnowledgeFileRequest
	8,  // 11: knowledge_file.v1.KnowledgeFileService.ListKnowledgeFiles:input_type -> knowledge_file.v1.ListKnowledgeFilesRequest
	10, // 12: knowledge_file.v1.KnowledgeFileService.DeleteKnowledgeFile:input_type -> knowledge_file.v1.DeleteKnowledgeFileRequest
	5,  // 13: knowledge_file.v1.KnowledgeFileService.CreateKnowledgeFile:output_type -> knowledge_file.v1.UploadFileStreamResponse
	7,  // 14: knowledge_file.v1.KnowledgeFileService.GetKnowledgeFile:output_type -> knowledge_file.v1.GetKnowledgeFileResponse
	9,  // 15: knowledge_file.v1.KnowledgeFileService.ListKnowledgeFiles:output_type -> knowledge_file.v1.ListKnowledgeFilesResponse
	11, // 16: knowledge_file.v1.KnowledgeFileService.DeleteKnowledgeFile:output_type -> knowledge_file.v1.DeleteKnowledgeFileResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_knowledge_file_proto_init() }
func file_knowledge_file_proto_init() {
	if File_knowledge_file_proto != nil {
		return
	}
	file_knowledge_file_proto_msgTypes[1].OneofWrappers = []any{}
	file_knowledge_file_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadFileStreamRequest_Metadata)(nil),
		(*UploadFileStreamRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledge_file_proto_rawDesc), len(file_knowledge_file_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledge_file_proto_goTypes,
		DependencyIndexes: file_knowledge_file_proto_depIdxs,
		EnumInfos:         file_knowledge_file_proto_enumTypes,
		MessageInfos:      file_knowledge_file_proto_msgTypes,
	}.Build()
	File_knowledge_file_proto = out.File
	file_knowledge_file_proto_goTypes = nil
	file_knowledge_file_proto_depIdxs = nil
}
