// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: rag.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RagSearchSimilarRequestDTO struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatbotId       string                 `protobuf:"bytes,2,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`
	QueryText       string                 `protobuf:"bytes,3,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	TopK            *int32                 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3,oneof" json:"top_k,omitempty"`
	KnowledgeFileId *string                `protobuf:"bytes,5,opt,name=knowledge_file_id,json=knowledgeFileId,proto3,oneof" json:"knowledge_file_id,omitempty"` // รองรับ `str | None` ด้วย optional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RagSearchSimilarRequestDTO) Reset() {
	*x = RagSearchSimilarRequestDTO{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchSimilarRequestDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchSimilarRequestDTO) ProtoMessage() {}

func (x *RagSearchSimilarRequestDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchSimilarRequestDTO.ProtoReflect.Descriptor instead.
func (*RagSearchSimilarRequestDTO) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *RagSearchSimilarRequestDTO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RagSearchSimilarRequestDTO) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *RagSearchSimilarRequestDTO) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *RagSearchSimilarRequestDTO) GetTopK() int32 {
	if x != nil && x.TopK != nil {
		return *x.TopK
	}
	return 0
}

func (x *RagSearchSimilarRequestDTO) GetKnowledgeFileId() string {
	if x != nil && x.KnowledgeFileId != nil {
		return *x.KnowledgeFileId
	}
	return ""
}

type RagResponseDTO struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	AnswerMessage string                       `protobuf:"bytes,1,opt,name=answer_message,json=answerMessage,proto3" json:"answer_message,omitempty"`
	Sources       []*SearchVectorRecordItemDTO `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"` // repeated = list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagResponseDTO) Reset() {
	*x = RagResponseDTO{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagResponseDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagResponseDTO) ProtoMessage() {}

func (x *RagResponseDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagResponseDTO.ProtoReflect.Descriptor instead.
func (*RagResponseDTO) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *RagResponseDTO) GetAnswerMessage() string {
	if x != nil {
		return x.AnswerMessage
	}
	return ""
}

func (x *RagResponseDTO) GetSources() []*SearchVectorRecordItemDTO {
	if x != nil {
		return x.Sources
	}
	return nil
}

type SearchVectorRecordItemDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Record        *VectorRecordDTO       `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVectorRecordItemDTO) Reset() {
	*x = SearchVectorRecordItemDTO{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVectorRecordItemDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorRecordItemDTO) ProtoMessage() {}

func (x *SearchVectorRecordItemDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorRecordItemDTO.ProtoReflect.Descriptor instead.
func (*SearchVectorRecordItemDTO) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *SearchVectorRecordItemDTO) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchVectorRecordItemDTO) GetRecord() *VectorRecordDTO {
	if x != nil {
		return x.Record
	}
	return nil
}

type VectorRecordDTO struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float32                `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Metadata      *MetadataVectorRecordDTO `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorRecordDTO) Reset() {
	*x = VectorRecordDTO{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRecordDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRecordDTO) ProtoMessage() {}

func (x *VectorRecordDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRecordDTO.ProtoReflect.Descriptor instead.
func (*VectorRecordDTO) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *VectorRecordDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorRecordDTO) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *VectorRecordDTO) GetMetadata() *MetadataVectorRecordDTO {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetadataVectorRecordDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatbotId     string                 `protobuf:"bytes,2,opt,name=chatbot_id,json=chatbotId,proto3" json:"chatbot_id,omitempty"`
	FileId        string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TextContent   string                 `protobuf:"bytes,5,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	PageNumber    int32                  `protobuf:"varint,6,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataVectorRecordDTO) Reset() {
	*x = MetadataVectorRecordDTO{}
	mi := &file_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataVectorRecordDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataVectorRecordDTO) ProtoMessage() {}

func (x *MetadataVectorRecordDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataVectorRecordDTO.ProtoReflect.Descriptor instead.
func (*MetadataVectorRecordDTO) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{4}
}

func (x *MetadataVectorRecordDTO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MetadataVectorRecordDTO) GetChatbotId() string {
	if x != nil {
		return x.ChatbotId
	}
	return ""
}

func (x *MetadataVectorRecordDTO) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *MetadataVectorRecordDTO) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *MetadataVectorRecordDTO) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *MetadataVectorRecordDTO) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *MetadataVectorRecordDTO) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\x06rag.v1\"\xde\x01\n" +
	"\x1aRagSearchSimilarRequestDTO\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x02 \x01(\tR\tchatbotId\x12\x1d\n" +
	"\n" +
	"query_text\x18\x03 \x01(\tR\tqueryText\x12\x18\n" +
	"\x05top_k\x18\x04 \x01(\x05H\x00R\x04topK\x88\x01\x01\x12/\n" +
	"\x11knowledge_file_id\x18\x05 \x01(\tH\x01R\x0fknowledgeFileId\x88\x01\x01B\b\n" +
	"\x06_top_kB\x14\n" +
	"\x12_knowledge_file_id\"t\n" +
	"\x0eRagResponseDTO\x12%\n" +
	"\x0eanswer_message\x18\x01 \x01(\tR\ranswerMessage\x12;\n" +
	"\asources\x18\x02 \x03(\v2!.rag.v1.SearchVectorRecordItemDTOR\asources\"b\n" +
	"\x19SearchVectorRecordItemDTO\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12/\n" +
	"\x06record\x18\x02 \x01(\v2\x17.rag.v1.VectorRecordDTOR\x06record\"v\n" +
	"\x0fVectorRecordDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.rag.v1.MetadataVectorRecordDTOR\bmetadata\"\xeb\x01\n" +
	"\x17MetadataVectorRecordDTO\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chatbot_id\x18\x02 \x01(\tR\tchatbotId\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftext_content\x18\x05 \x01(\tR\vtextContent\x12\x1f\n" +
	"\vpage_number\x18\x06 \x01(\x05R\n" +
	"pageNumber\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename2Y\n" +
	"\n" +
	"RagService\x12K\n" +
	"\rSearchSimilar\x12\".rag.v1.RagSearchSimilarRequestDTO\x1a\x16.rag.v1.RagResponseDTOBAZ?github.com/ballinwza/scraper-dashboard-be/api/proto/v1;grpc_apib\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rag_proto_goTypes = []any{
	(*RagSearchSimilarRequestDTO)(nil), // 0: rag.v1.RagSearchSimilarRequestDTO
	(*RagResponseDTO)(nil),             // 1: rag.v1.RagResponseDTO
	(*SearchVectorRecordItemDTO)(nil),  // 2: rag.v1.SearchVectorRecordItemDTO
	(*VectorRecordDTO)(nil),            // 3: rag.v1.VectorRecordDTO
	(*MetadataVectorRecordDTO)(nil),    // 4: rag.v1.MetadataVectorRecordDTO
}
var file_rag_proto_depIdxs = []int32{
	2, // 0: rag.v1.RagResponseDTO.sources:type_name -> rag.v1.SearchVectorRecordItemDTO
	3, // 1: rag.v1.SearchVectorRecordItemDTO.record:type_name -> rag.v1.VectorRecordDTO
	4, // 2: rag.v1.VectorRecordDTO.metadata:type_name -> rag.v1.MetadataVectorRecordDTO
	0, // 3: rag.v1.RagService.SearchSimilar:input_type -> rag.v1.RagSearchSimilarRequestDTO
	1, // 4: rag.v1.RagService.SearchSimilar:output_type -> rag.v1.RagResponseDTO
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	file_rag_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
